const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {COUNTRIES,CURRENCIES,globalTemplate,GlobalRulesSchema,previewWorldwide}=require('../dist/services/payrollRules/worldwide');
const {RulesSchema,rulesHash,previewPayroll}=require('../dist/services/payrollRules/engine');
// These are hypothetical company rules for testing arithmetic, not statutory country tables.
const fixture=(country='GB',currency='GBP')=>({...globalTemplate(),country,currency,subdivision:'Test region',review:{reviewer:'Test reviewer',reference:'Synthetic arithmetic fixture, not tax law',reviewedOn:'2026-09-01',confirmed:true}});
const line=(overrides={})=>({id:'test',label:'Synthetic deduction',category:'tax',method:'percentage',basis:'taxable',period:'pay_period',amount:0,rate:.1,exemption:0,credit:0,annualCap:null,brackets:[{above:0,rate:0}],...overrides});
const input={payDate:'2026-09-01',gross:3000,taxable:3000,manualAmounts:{},ytd:{},reviewReference:'Independent synthetic payroll check',companyRulesConfirmed:true};
test('country metadata covers 249 territories without certifying tax support',()=>{assert.equal(COUNTRIES.length,249);assert.equal(new Set(COUNTRIES.map(c=>c.code)).size,249);assert.equal(CURRENCIES.find(c=>c.code==='JPY').decimals,0);assert.equal(CURRENCIES.find(c=>c.code==='KWD').decimals,3);assert.equal(CURRENCIES.find(c=>c.code==='IQD').decimals,3);assert.equal(CURRENCIES.find(c=>c.code==='AFN').decimals,2);assert.equal(CURRENCIES.find(c=>c.code==='CLF').decimals,4);assert.equal(GlobalRulesSchema.safeParse(globalTemplate()).success,false);});
test('worldwide dispatch retains custom classification and hashes canonical rules',()=>{const rules=fixture();rules.lines=[line()];const r=previewPayroll(rules,input);assert.equal(r.net,'2700.00');assert.equal(r.classification,'custom_rules_review_required');assert.equal(r.rulesHash,rulesHash(rules));assert.equal(r.verified,false);assert.equal(r.cpp,'0.00');assert.equal(r.ei,'0.00');assert.equal(RulesSchema.safeParse(rules).success,true);});
test('marginal tax brackets apply only to each income slice',()=>{const rules=fixture();rules.lines=[line({method:'progressive',brackets:[{above:0,rate:0},{above:1000,rate:.1},{above:2000,rate:.2}]})];assert.equal(previewWorldwide(rules,input).incomeTax,'300.00');assert.equal(previewWorldwide(rules,{...input,gross:1000,taxable:1000}).incomeTax,'0.00');});
test('annualization, exemption and payment credit are explicit',()=>{const rules=fixture();rules.lines=[line({period:'annualized',method:'progressive',exemption:1200,credit:5,brackets:[{above:0,rate:0},{above:12000,rate:.2}]})];const r=previewWorldwide(rules,input);assert.equal(r.incomeTax,'375.00');assert.equal(r.net,'2625.00');});
test('employer contributions never reduce employee net and annual caps use required YTD',()=>{const rules=fixture();rules.lines=[line(),line({id:'employee',category:'employee_contribution',annualCap:500}),line({id:'employer',category:'employer_contribution',rate:.2})];const r=previewWorldwide(rules,{...input,ytd:{employee:450}});assert.equal(r.employeeContributions,'50.00');assert.equal(r.employerContributions,'600.00');assert.equal(r.net,'2650.00');assert.equal(r.employerCost,'3600.00');assert.throws(()=>previewWorldwide(rules,input),/required/);assert.throws(()=>previewWorldwide(rules,{...input,ytd:{employee:501}}),/cap|YTD/);});
test('reviewed manual figures are mandatory and never replaced with assumed zero tax',()=>{const rules=fixture('JP','JPY');assert.throws(()=>previewWorldwide(rules,input),/required/);const r=previewWorldwide(rules,{...input,manualAmounts:{income_tax:123}});assert.equal(r.incomeTax,'123');assert.equal(r.net,'2877');assert.throws(()=>previewWorldwide(rules,{...input,manualAmounts:{income_tax:123.5}}),/minor units/);assert.throws(()=>previewWorldwide(rules,{...input,manualAmounts:{income_tax:1,unexpected:1}}),/required/);});
test('currency precision preserves yen and three-decimal dinars',()=>{let rules=fixture('JP','JPY');rules.lines=[line({rate:.005})];assert.equal(previewWorldwide(rules,{...input,gross:100,taxable:100}).incomeTax,'1');rules=fixture('KW','KWD');rules.lines=[line({rate:.001})];const r=previewWorldwide(rules,{...input,gross:100.125,taxable:100.125});assert.equal(r.incomeTax,'0.100');assert.equal(r.net,'100.025');assert.throws(()=>previewWorldwide(rules,{...input,gross:100.0001}),/minor units/);rules=fixture('CL','CLF');rules.lines=[line({rate:.1})];assert.equal(previewWorldwide(rules,{...input,gross:1.2345,taxable:1.2345}).net,'1.1110');});
test('invalid countries, dates, duplicate lines, missing tax and negative net reject',()=>{const rules=fixture();rules.lines=[line()];assert.equal(GlobalRulesSchema.safeParse({...rules,country:'ZZ'}).success,false);assert.equal(GlobalRulesSchema.safeParse({...rules,review:{...rules.review,confirmed:false}}).success,false);assert.equal(GlobalRulesSchema.safeParse({...rules,lines:[line(),line()]}).success,false);assert.equal(GlobalRulesSchema.safeParse({...rules,lines:[line({category:'employer_contribution'})]}).success,false);assert.throws(()=>previewWorldwide(rules,{...input,payDate:'2026-02-30'}));assert.throws(()=>previewWorldwide(rules,{...input,payDate:'2027-01-01'}));rules.lines=[line({method:'fixed',amount:4000})];assert.throws(()=>previewWorldwide(rules,input),/exceed/);});
const {PGlite}=require('@electric-sql/pglite'),express=require('express');process.env.JWT_SECRET='isolated-worldwide-test-secret';const jwt=require('jsonwebtoken'),{pool}=require('../dist/config/database');const db=new PGlite();let server,base;const id=n=>`00000000-0000-4000-a000-${String(n).padStart(12,'0')}`;const query=async(sql,args)=>{const r=await db.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows||r.rows.length};};
async function req(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+jwt.sign({id:id(2)},process.env.JWT_SECRET)},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
before(async()=>{await db.exec(`CREATE TABLE companies(id uuid PRIMARY KEY);CREATE TABLE users(id uuid PRIMARY KEY,company_id uuid,role text,is_active boolean DEFAULT true,first_name text,last_name text);CREATE TABLE payrolls(id uuid PRIMARY KEY,company_id uuid,period_start date,period_end date,total_hours numeric,total_pay numeric(14,2),status text,updated_at timestamptz);CREATE TABLE payroll_items(id uuid PRIMARY KEY,payroll_id uuid REFERENCES payrolls(id),employee_id uuid,hours numeric,hourly_rate numeric,adjustments numeric(14,2),cpp_deduction numeric,ei_deduction numeric,tax_deduction numeric);`);for(const name of ['20260930_payroll_rules.sql','20261001_worldwide_payroll_records.sql']){const sql=fs.readFileSync(require('node:path').join(__dirname,'../migrations',name),'utf8');await db.exec(sql);await db.exec(sql);}await query('INSERT INTO companies VALUES($1)',[id(1)]);await query("INSERT INTO users(id,company_id,role) VALUES($1,$2,'boss')",[id(2),id(1)]);await query("INSERT INTO payrolls(id,company_id,status) VALUES($1,$2,'draft')",[id(3),id(1)]);await query('INSERT INTO payroll_items(id,payroll_id,employee_id,hours,hourly_rate) VALUES($1,$2,$3,1,100)',[id(4),id(3),id(2)]);pool.query=query;pool.connect=async()=>({query,release(){}});const app=express();app.use(express.json());app.use('/rules',require('../dist/routes/payrollRulesRoutes').default);app.use('/manual',require('../dist/routes/manualPayrollRoutes').default);app.use('/year-end',require('../dist/routes/yearEndRouter').default);server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{if(server)await new Promise(r=>server.close(r));await db.close();await pool.end();});
test('worldwide rules save and three-decimal payroll completes review/payment without precision loss',async()=>{const rules=fixture('KW','KWD');rules.lines=[line({rate:.001})];assert.equal((await req('/rules',{rules,expectedRevision:0,reason:'Synthetic KWD precision test'})).status,201);const p='/manual/'+id(3);const result=await req(p+'/calculate',{itemId:id(4),rulesRevision:1,input:{...input,gross:100.125,taxable:100.125}});assert.equal(result.status,200,JSON.stringify(result));assert.equal(result.data.result.net,'100.025');assert.equal((await req('/year-end/preview')).status,409);assert.equal((await req('/year-end/finalize',{taxYear:2026})).status,409);assert.equal((await req(p+'/review',{reference:'Independent fixture review only',confirmed:true})).status,200);const detail=(await req(p)).data;assert.equal(detail.payroll.manual_review.netTotal,'100.025');assert.equal(detail.payroll.manual_review.currency,'KWD');const payment={itemId:id(4),paidOn:input.payDate,amount:'100.025',reference:'TEST-ONLY-NO-BANK',confirmed:true};assert.equal((await req(p+'/record-payment',payment)).status,200);assert.equal((await req(p+'/record-payment',payment)).status,200);assert.equal((await query('SELECT amount FROM manual_payroll_payments')).rows[0].amount,'100.0250');assert.equal((await req('/rules',{rules:fixture('GB','GBP'),expectedRevision:1,reason:'Attempt to mix currencies'})).status,422);});

test('all listed countries and currency minor units accept explicitly reviewed manual fixtures',()=>{for(const c of COUNTRIES){const rules=fixture(c.code,'USD');assert.equal(previewWorldwide(rules,{...input,manualAmounts:{income_tax:1}}).net,'2999.00');}for(const c of CURRENCIES){const rules=fixture('GB',c.code);assert.equal(previewWorldwide(rules,{...input,manualAmounts:{income_tax:1}}).net,Number(2999).toFixed(c.decimals));}});
