import { pool } from '../config/database';
import { CompanyActor,manages } from '../middleware/companyActor';
import { createHash } from 'crypto';
const canonical=(v:any):string=>JSON.stringify(v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,JSON.parse(canonical(v[k]))])):Array.isArray(v)?v.map(x=>JSON.parse(canonical(x))):v);
export class OpsError extends Error { constructor(message:string,public status=400){super(message);} }
export const check=(ok:unknown,message:string,status=400)=>{if(!ok)throw new OpsError(message,status);};
export const manager=(a:CompanyActor)=>check(manages(a),'Manager access required',403);
export const uuid=(v:any)=>{check(typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v),'Valid record ID required');return v;};
export const text=(v:any,max=200)=>{check(typeof v==='string'&&v.trim().length>0&&v.length<=max,`Text must contain 1–${max} characters`);return v.trim();};
export const num=(v:any,min:number,max:number)=>{check(v!==''&&v!==null&&typeof v!=='boolean'&&Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max,`Number must be between ${min} and ${max}`);return Number(v);};
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export async function transaction<T>(work:(c:any)=>Promise<T>):Promise<T>{const c=await pool.connect();try{await c.query('BEGIN');const result=await work(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function companyLock(c:any,id:string){await c.query('SELECT id FROM companies WHERE id=$1 FOR UPDATE',[id]);}
export async function project(c:any,a:CompanyActor,id:string){const r=await c.query('SELECT id,name FROM projects WHERE id=$1 AND company_id=$2',[uuid(id),a.company_id]);check(r.rowCount,'Project unavailable',404);return r.rows[0];}
export async function person(c:any,a:CompanyActor,id:string){const r=await c.query('SELECT id FROM users WHERE id=$1 AND company_id=$2 AND COALESCE(is_active,true)',[uuid(id),a.company_id]);check(r.rowCount,'Employee unavailable',404);}
// Request keys are scoped to actor and tenant. Reuse with another payload is a conflict, never a second mutation.
export async function action(a:CompanyActor,kind:string,key:string,payload:any,work:(c:any)=>Promise<any>){
 manager(a);text(key,100);return transaction(async c=>{await companyLock(c,a.company_id);
 const prior=await c.query('SELECT * FROM ops_actions WHERE company_id=$1 AND actor_id=$2 AND request_key=$3',[a.company_id,a.id,key]);
 if(prior.rowCount){check(prior.rows[0].kind===kind&&canonical(prior.rows[0].payload)===canonical(payload), 'Request key already used for another action',409);return {actionId:prior.rows[0].id,...prior.rows[0].result,replayed:true,state:prior.rows[0].state};}
 const result=await work(c);const r=await c.query('INSERT INTO ops_actions(company_id,actor_id,kind,request_key,payload,result) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[a.company_id,a.id,kind,key,JSON.stringify(payload),JSON.stringify(result)]);
 return {actionId:r.rows[0].id,...result};});
}
export async function consumeAI(a:CompanyActor){return transaction(async c=>{await companyLock(c,a.company_id);const l=await c.query('SELECT * FROM ops_limits WHERE company_id=$1',[a.company_id]);check(l.rowCount,'AI allowance has not been configured by the service operator',409);
 const r=await c.query(`INSERT INTO ops_usage(company_id,month,ai_requests) SELECT $1,date_trunc('month',now())::date,1 WHERE $2>0 ON CONFLICT(company_id,month) DO UPDATE SET ai_requests=ops_usage.ai_requests+1 WHERE ops_usage.ai_requests<$2 RETURNING ai_requests`,[a.company_id,l.rows[0].monthly_ai_requests]);check(r.rowCount,'Monthly AI request allowance reached',429);});}
export async function capacity(c:any,company:string,extra:number){const l=await c.query('SELECT employees FROM ops_limits WHERE company_id=$1',[company]);check(l.rowCount,'Employee allowance has not been configured by the service operator',409);const r=await c.query(`SELECT (SELECT count(*) FROM users WHERE company_id=$1 AND COALESCE(is_active,true))+(SELECT count(*) FROM ops_invites WHERE company_id=$1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at>now()) n`,[company]);check(Number(r.rows[0].n)+extra<=l.rows[0].employees,'Employee allowance reached',409);}
export function parseCSV(source:string){check(source.length<=200000,'CSV exceeds 200 KB');const rows:string[][]=[];let row:string[]=[],field='',quoted=false;
 for(let i=0;i<source.length;i++){const ch=source[i];if(ch==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++;}else{check(quoted||field.length===0,'Invalid CSV quote');quoted=!quoted;}}else if(!quoted&&(ch===','||ch==='\n')){row.push(field.replace(/\r$/,''));field='';if(ch==='\n'){if(row.some(Boolean))rows.push(row);row=[];}}else field+=ch;}check(!quoted,'Unclosed CSV quote');row.push(field.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);
 check(rows.length>=2&&rows.length<=201,'Import 1–200 employees per batch');check(rows.shift()!.map(x=>x.trim().toLowerCase()).join(',')==='first_name,last_name,email','CSV header must be first_name,last_name,email');const seen=new Set();return rows.map((r,i)=>{check(r.length===3,`Row ${i+2}: expected three columns`);const firstName=text(r[0],80),lastName=text(r[1],80),email=text(r[2],254).toLowerCase();check(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),`Row ${i+2}: invalid email`);check(!seen.has(email),`Row ${i+2}: duplicate email`);seen.add(email);return {firstName,lastName,email};});}
export async function searchDocuments(a:CompanyActor,q:string){const query=text(q,500);const r=await pool.query(`SELECT id,title,created_at,body FROM ops_documents WHERE company_id=$1 AND ($2 OR audience='company') AND to_tsvector('english',body) @@ plainto_tsquery('english',$3) ORDER BY ts_rank(to_tsvector('english',body),plainto_tsquery('english',$3)) DESC LIMIT 5`,[a.company_id,manages(a),query]);
 return {answer:r.rowCount?'Matching source passages; these are excerpts, not an AI interpretation.':'No matching company document found. Try a more specific term.',sources:r.rows.map(x=>{const tokens=query.toLowerCase().match(/[a-z]{3,}/g)||[];const lines=x.body.split(/\n|(?<=[.!?])\s+/);return {id:x.id,title:x.title,createdAt:x.created_at,excerpt:lines.filter((l:string)=>tokens.some(t=>l.toLowerCase().includes(t))).join(' ').slice(0,1800)||x.body.slice(0,1800)};})};}
export async function profitability(a:CompanyActor){manager(a);const r=await pool.query(`SELECT b.*,p.name,
 (SELECT sum(COALESCE(te.total_wage,0)) FROM time_entries te JOIN users u ON u.id=te.user_id WHERE te.project_id=b.project_id AND u.company_id=b.company_id AND te.approval_status='approved') labor,
 (SELECT count(*) FROM time_entries te JOIN users u ON u.id=te.user_id WHERE te.project_id=b.project_id AND u.company_id=b.company_id AND (te.approval_status IS DISTINCT FROM 'approved' OR te.total_wage IS NULL OR te.clock_out IS NULL)) incomplete_entries,
 (SELECT sum(e.amount) FROM expense_claims e WHERE e.project_id=b.project_id AND e.company_id=b.company_id AND e.status='approved' AND e.currency=b.currency) expenses,
 (SELECT count(*) FROM expense_claims e WHERE e.project_id=b.project_id AND e.company_id=b.company_id AND e.status='approved' AND e.currency<>b.currency) currency_exclusions
 FROM ops_budgets b JOIN projects p ON p.id=b.project_id AND p.company_id=b.company_id WHERE b.company_id=$1 ORDER BY p.name`,[a.company_id]);
 return r.rows.map(x=>{const cost=(Number(x.labor||0)+Number(x.expenses||0))*(1+Number(x.overhead_percent)/100),forecast=cost/(Number(x.progress)/100);return {...x,actualCost:Math.round(cost*100)/100,forecastCost:Math.round(forecast*100)/100,forecastProfit:Math.round((Number(x.revenue)-forecast)*100)/100,overBudget:forecast>Number(x.budget),method:'Linear cost-to-complete from manager-entered progress; not a statistical prediction. Wages and budget must share a currency.'};});}
export async function snapshot(c:any,company:string){const r=await c.query(`SELECT (SELECT count(*) FROM tasks WHERE company_id=$1 AND COALESCE(status,'pending') NOT IN ('completed','done')) open_tasks,(SELECT count(*) FROM expense_claims WHERE company_id=$1 AND status='pending') pending_expenses,(SELECT count(*) FROM time_entries t JOIN users u ON u.id=t.user_id WHERE u.company_id=$1 AND t.approval_status IS DISTINCT FROM 'approved') timesheets_needing_review`,[company]);return {generatedAt:new Date().toISOString(),...r.rows[0]};}
export async function runDueReports(){return transaction(async c=>{const jobs=await c.query(`SELECT s.* FROM ops_report_schedules s JOIN users u ON u.id=s.created_by WHERE s.enabled AND s.next_at<=now() AND u.company_id=s.company_id AND COALESCE(u.is_active,true) AND lower(u.role) IN ('boss','manager','admin') ORDER BY s.next_at LIMIT 25 FOR UPDATE OF s SKIP LOCKED`);for(const job of jobs.rows){await c.query('INSERT INTO ops_reports(company_id,schedule_id,scheduled_for,data) VALUES($1,$2,$3,$4) ON CONFLICT(schedule_id,scheduled_for) DO NOTHING',[job.company_id,job.id,job.next_at,JSON.stringify(await snapshot(c,job.company_id))]);await c.query(`UPDATE ops_report_schedules SET next_at=now()+CASE WHEN cadence='daily' THEN interval '1 day' ELSE interval '7 days' END WHERE id=$1`,[job.id]);}return jobs.rowCount;});}
