import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

interface PhotoData {
  id: string;
  s3_key: string;
  taken_at: string;
  taken_by?: string;
  compliance_score?: number;
  verification_hash?: string;
}

export async function generateEvidenceReport(
  photos: PhotoData[],
  title: string,
  companyName: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(22).font('Helvetica-Bold').text(title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).font('Helvetica').text(`Generated by: ${companyName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Total Photos: ${photos.length}`);
      doc.moveDown(2);

      // Table header
      const tableTop = doc.y;
      doc.font('Helvetica-Bold')
        .text('Photo ID', 50, tableTop, { width: 100 })
        .text('Date/Time', 150, tableTop, { width: 150 })
        .text('Taken By', 300, tableTop, { width: 120 })
        .text('Score', 420, tableTop, { width: 60 })
        .text('Verified', 480, tableTop, { width: 80 });

      doc.moveDown();
      const lineY = doc.y;
      doc.moveTo(50, lineY).lineTo(550, lineY).stroke();
      doc.moveDown();

      // Rows
      photos.forEach((photo, index) => {
        const y = doc.y;
        const date = new Date(photo.taken_at).toLocaleString();
        const score = photo.compliance_score || 0;
        const verified = photo.verification_hash ? '✅ Yes' : '❌ No';

        doc.font('Helvetica')
          .text(`${index + 1}`, 50, y, { width: 100 })
          .text(date, 150, y, { width: 150 })
          .text(photo.taken_by || 'Unknown', 300, y, { width: 120 })
          .text(`${score}%`, 420, y, { width: 60 })
          .text(verified, 480, y, { width: 80 });

        // Add a small thumbnail if we have the URL (we'll just show a placeholder)
        // Optionally, you could download the image and embed it, but that's heavy.
        // We'll leave as is for performance.

        doc.moveDown();
        // Add a separator line between rows
        if (index < photos.length - 1) {
          const sepY = doc.y;
          doc.moveTo(50, sepY).lineTo(550, sepY).stroke('#DDD');
          doc.moveDown();
        }
      });

      // Footer
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(10)
          .text(
            `Page ${i + 1} of ${pageCount} – ${new Date().toISOString().split('T')[0]}`,
            50,
            doc.page.height - 50,
            { align: 'center', width: 500 }
          );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}