import React from 'react';
import { renderToBuffer } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import path from 'path';
import fs from 'fs';
import { pool } from '../config/database';

const PDF_DIR = path.join(__dirname, '../../pdfs');
if (!fs.existsSync(PDF_DIR)) {
  fs.mkdirSync(PDF_DIR, { recursive: true });
}

// ─── Styles ─────────────────────────────────────────────────────
const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  section: { marginBottom: 12 },
  label: { fontWeight: 'bold', marginBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  field: { flex: 1 },
  value: { flex: 2 },
});

// ─── Helper: Calculate annual totals ────────────────────────────
export async function getEmployeeAnnualTotals(employeeId: string, year: number) {
  const result = await pool.query(
    `SELECT
       COALESCE(SUM(pi.pay), 0) as total_income,
       COALESCE(SUM(pi.tax_deduction), 0) as tax_deductions,
       COALESCE(SUM(pi.cpp_deduction), 0) as cpp,
       COALESCE(SUM(pi.ei_deduction), 0) as ei
     FROM payroll_items pi
     JOIN payrolls p ON pi.payroll_id = p.id
     WHERE pi.employee_id = $1
       AND EXTRACT(YEAR FROM p.period_start) = $2`,
    [employeeId, year]
  );
  return result.rows[0];
}

// ─── Generate T4 PDF ─────────────────────────────────────────────
export async function generateT4PDF(employee: any, year: number): Promise<string> {
  const totals = await getEmployeeAnnualTotals(employee.id, year);
  const filename = `t4_${employee.id}_${year}.pdf`;
  const filepath = path.join(PDF_DIR, filename);

  const T4Document = () =>
    React.createElement(
      Document,
      null,
      React.createElement(
        Page,
        { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.header }, 'T4 – Statement of Remuneration Paid'),
        React.createElement(Text, { style: { marginBottom: 10 } }, `Year: ${year}`),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Employee Information'),
          React.createElement(Text, null, `Name: ${employee.first_name} ${employee.last_name}`),
          React.createElement(Text, null, `Email: ${employee.email}`),
          React.createElement(Text, null, `SIN: ${employee.sin || 'Not provided'}`)
        ),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Income and Deductions'),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'Total Income:'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.total_income).toFixed(2)}`)
          ),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'Tax Deductions:'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.tax_deductions).toFixed(2)}`)
          ),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'CPP Contributions:'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.cpp).toFixed(2)}`)
          ),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'EI Premiums:'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.ei).toFixed(2)}`)
          )
        ),
        React.createElement(
          Text,
          { style: { marginTop: 20, fontSize: 9, color: '#888' } },
          `Generated by Future Jobs Pro AI on ${new Date().toLocaleDateString()}`
        )
      )
    );

  const pdfBuffer = await renderToBuffer(React.createElement(T4Document));
  fs.writeFileSync(filepath, pdfBuffer);
  return `/pdfs/${filename}`;
}

// ─── Generate RL-1 PDF ──────────────────────────────────────────
export async function generateRL1PDF(employee: any, year: number): Promise<string> {
  const totals = await getEmployeeAnnualTotals(employee.id, year);
  const filename = `rl1_${employee.id}_${year}.pdf`;
  const filepath = path.join(PDF_DIR, filename);

  const RL1Document = () =>
    React.createElement(
      Document,
      null,
      React.createElement(
        Page,
        { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.header }, 'RL-1 – Relevé 1 (Québec)'),
        React.createElement(Text, { style: { marginBottom: 10 } }, `Year: ${year}`),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Employee Information'),
          React.createElement(Text, null, `Name: ${employee.first_name} ${employee.last_name}`),
          React.createElement(Text, null, `Email: ${employee.email}`),
          React.createElement(Text, null, `SIN: ${employee.sin || 'Not provided'}`)
        ),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Income and Deductions'),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'Total Income (Box A):'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.total_income).toFixed(2)}`)
          ),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'Québec Pension Plan (QPP):'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.cpp).toFixed(2)}`)
          ),
          React.createElement(
            View,
            { style: styles.row },
            React.createElement(Text, { style: styles.field }, 'EI Premiums (QE):'),
            React.createElement(Text, { style: styles.value }, `$${Number(totals.ei).toFixed(2)}`)
          )
        ),
        React.createElement(
          Text,
          { style: { marginTop: 20, fontSize: 9, color: '#888' } },
          `Generated by Future Jobs Pro AI on ${new Date().toLocaleDateString()}`
        )
      )
    );

  const pdfBuffer = await renderToBuffer(React.createElement(RL1Document));
  fs.writeFileSync(filepath, pdfBuffer);
  return `/pdfs/${filename}`;
}