import React from 'react';
import { renderToBuffer } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import path from 'path';
import fs from 'fs';
import { v4 as uuidv4 } from 'uuid';

const PDF_DIR = path.join(__dirname, '../../pdfs');
if (!fs.existsSync(PDF_DIR)) {
  fs.mkdirSync(PDF_DIR, { recursive: true });
}

// ─── PDF Styles ─────────────────────────────────────────────────
const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  section: { marginBottom: 12 },
  label: { fontWeight: 'bold', marginBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  field: { flex: 1 },
  value: { flex: 2 },
  table: { marginTop: 16 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#EEE', padding: 4 },
  tableRow: { flexDirection: 'row', borderBottom: '1px solid #EEE', padding: 4 },
  cell: { flex: 1, fontSize: 10 },
});

// ─── T4 PDF ─────────────────────────────────────────────────────
interface T4Data {
  employeeId: string;
  year: number;
  totalIncome: number;
  taxDeductions: number;
  cpp: number;
  ei: number;
  // ... add more fields as needed
}

export async function generateT4PDF(data: T4Data, employee: any): Promise<string> {
  const filename = `t4_${employee.id}_${data.year}.pdf`;
  const filepath = path.join(PDF_DIR, filename);

  const T4Document = (): React.ReactElement => {
    return React.createElement(
      Document,
      null,
      React.createElement(
        Page,
        { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.header }, 'T4 – Statement of Remuneration Paid'),
        React.createElement(Text, { style: { marginBottom: 10 } }, `Year: ${data.year}`),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Employee Information'),
          React.createElement(Text, null, `Name: ${employee.first_name} ${employee.last_name}`),
          React.createElement(Text, null, `Email: ${employee.email}`),
          React.createElement(Text, null, `SIN: ${employee.sin || 'Not provided'}`),
        ),
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.label }, 'Income and Deductions'),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'Total Income:'), React.createElement(Text, { style: styles.value }, `$${data.totalIncome.toFixed(2)}`)),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'Tax Deductions:'), React.createElement(Text, { style: styles.value }, `$${data.taxDeductions.toFixed(2)}`)),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'CPP Contributions:'), React.createElement(Text, { style: styles.value }, `$${data.cpp.toFixed(2)}`)),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'EI Premiums:'), React.createElement(Text, { style: styles.value }, `$${data.ei.toFixed(2)}`)),
        ),
        React.createElement(Text, { style: { marginTop: 20, fontSize: 9, color: '#888' } }, `Generated by Future Jobs Pro AI on ${new Date().toLocaleDateString()}`),
      ),
    );
  };

  const pdfBuffer = await renderToBuffer(React.createElement(T4Document));
  fs.writeFileSync(filepath, pdfBuffer);
  return `/pdfs/${filename}`;
}

// ─── RL-1 PDF ───────────────────────────────────────────────────
export async function generateRL1PDF(data: T4Data, employee: any): Promise<string> {
  const filename = `rl1_${employee.id}_${data.year}.pdf`;
  const filepath = path.join(PDF_DIR, filename);

  const RL1Document = () => React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: 'A4', style: styles.page },
      React.createElement(Text, { style: styles.header }, 'RL-1 – Relevé 1 (Québec)'),
      React.createElement(Text, { style: { marginBottom: 10 } }, `Year: ${data.year}`),
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.label }, 'Employee Information'),
        React.createElement(Text, null, `Name: ${employee.first_name} ${employee.last_name}`),
        React.createElement(Text, null, `Email: ${employee.email}`),
        React.createElement(Text, null, `SIN: ${employee.sin || 'Not provided'}`),
      ),
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.label }, 'Income and Deductions'),
        React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'Total Income (Box A):'), React.createElement(Text, { style: styles.value }, `$${data.totalIncome.toFixed(2)}`)),
        React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'Québec Pension Plan (QPP):'), React.createElement(Text, { style: styles.value }, `$${data.cpp.toFixed(2)}`)),
        React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.field }, 'EI Premiums (QE):'), React.createElement(Text, { style: styles.value }, `$${data.ei.toFixed(2)}`)),
      ),
      React.createElement(Text, { style: { marginTop: 20, fontSize: 9, color: '#888' } }, `Generated by Future Jobs Pro AI on ${new Date().toLocaleDateString()}`),
    ),
  );

  const pdfBuffer = await renderToBuffer(React.createElement(RL1Document));
  fs.writeFileSync(filepath, pdfBuffer);
  return `/pdfs/${filename}`;
}