import { pool } from '../config/database';
type Summary={gross:number;cpp:number;ei:number;tax:number;vacationPay:number};

async function context(employeeId:string|number,taxYear:number,companyId?:string){
 if(!companyId)throw new Error('Authenticated company context is required');
 if(!Number.isInteger(taxYear)||taxYear<2000||taxYear>new Date().getFullYear()+1)throw new Error('Invalid tax year');
 const identityResult=await pool.query(`SELECT u.first_name,u.last_name,u.email,u.sin,u.province employee_province,c.name company_name,c.legal_name,c.business_number,c.payroll_account_number,c.address company_address,c.city company_city,c.province company_province,c.postal_code,c.phone,c.email company_email FROM users u JOIN companies c ON c.id=u.company_id WHERE u.id=$1 AND c.id=$2`,[employeeId,companyId]);
 if(!identityResult.rowCount)throw new Error('Employee was not found in your company');
 const totals=await pool.query(`SELECT COALESCE(SUM(COALESCE(pi.hours,0)*COALESCE(pi.hourly_rate,0)+COALESCE(pi.vacation_pay,0)),0) gross,COALESCE(SUM(pi.cpp_deduction),0) cpp,COALESCE(SUM(pi.ei_deduction),0) ei,COALESCE(SUM(pi.tax_deduction),0) tax,COALESCE(SUM(pi.vacation_pay),0) vacation_pay FROM payroll_items pi JOIN payrolls p ON p.id=pi.payroll_id WHERE pi.employee_id=$1 AND p.company_id=$2 AND EXTRACT(YEAR FROM p.period_end)=$3 AND p.status IN ('approved','processed','paid')`,[employeeId,companyId,taxYear]);
 const i=identityResult.rows[0],t=totals.rows[0]||{};const summary:Summary={gross:Number(t.gross||0),cpp:Number(t.cpp||0),ei:Number(t.ei||0),tax:Number(t.tax||0),vacationPay:Number(t.vacation_pay||0)};
 return{summary,employer:{name:i.legal_name||i.company_name,businessNumber:i.business_number,payrollAccountNumber:i.payroll_account_number,address:i.company_address,city:i.company_city,province:i.company_province,postalCode:i.postal_code,phone:i.phone,email:i.company_email},employee:{firstName:i.first_name,lastName:i.last_name,email:i.email,maskedSin:i.sin?`*** *** ${String(i.sin).replace(/\D/g,'').slice(-3)}`:null,province:i.employee_province}};
}

export async function compileT4Slip(employeeId:string|number,taxYear:number,companyId?:string){const c=await context(employeeId,taxYear,companyId);return{employer:c.employer,employee:c.employee,t4Manifest:{box14_employment_income:c.summary.gross,box16_cpp_withheld:c.summary.cpp,box18_ei_withheld:c.summary.ei,box22_income_tax_withheld:c.summary.tax,box24_insurable_earnings:c.summary.gross,box26_pensionable_earnings:c.summary.gross,box44_union_dues:0,box46_charitable_donations:0,box52_pension_adjustment:0,vacation_pay_included:c.summary.vacationPay},employerMetrics:{employer_cpp_matching:c.summary.cpp,employer_ei_matching:Number((c.summary.ei*1.4).toFixed(2))},source:'approved or paid payroll records'};}
export async function compileT4ASlip(employeeId:string|number,taxYear:number,companyId?:string){const c=await context(employeeId,taxYear,companyId);return{employer:c.employer,employee:c.employee,t4aManifest:{box020_self_employed_fees:c.summary.gross,box022_income_tax_withheld:c.summary.tax},source:'approved or paid payroll records'};}
export async function compileRL1Slip(employeeId:string|number,taxYear:number,companyId?:string){const c=await context(employeeId,taxYear,companyId);return{employer:c.employer,employee:c.employee,rl1Manifest:{box_a_employment_income:c.summary.gross,box_b_qpp_contribution:c.summary.cpp,box_c_qpip_premium:c.summary.ei,box_e_quebec_tax_withheld:c.summary.tax,box_g_pensionable_earnings:c.summary.gross,box_i_insurable_earnings:c.summary.gross},source:'approved or paid payroll records'};}
