import React,{useEffect,useState} from 'react';
import {ScrollView,View,Text,TextInput,TouchableOpacity,Switch,StyleSheet} from 'react-native';
import WorldwidePayrollRules from './WorldwidePayrollRules';
import {api} from '../services/api';
const label=(s:string)=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());
export default function PayrollRulesScreen(){
 const [metadata,setMetadata]=useState<any>(null);
 const [rules,setRules]=useState<any>(null),[revision,setRevision]=useState(0),[history,setHistory]=useState<any[]>([]),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null);
 const [input,setInput]=useState<any>({payDate:new Date().toISOString().slice(0,10),gross:2000,cppYtd:0,cpp2Ytd:0,eiYtd:0,pensionableYtd:0,additionalTax:0,standardCaseConfirmed:false});
 const load=async()=>{const d:any=await api.get('/payroll-rules');setMetadata(d);setRules(d.current?.rules||d.template);setRevision(d.current?.revision||0);setHistory(d.history);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();}catch(e:any){setNotice(e.response?.data?.message||e.message||'Request failed');}finally{setBusy(false);}};
 useEffect(()=>{void run(load);},[]);
 const button=(text:string,fn:()=>void,disabled=false)=><TouchableOpacity accessibilityRole="button" disabled={busy||disabled} onPress={fn} style={[styles.button,(busy||disabled)&&{opacity:.4}]}><Text style={styles.buttonText}>{text}</Text></TouchableOpacity>;
 const field=(key:string,value:any,change:(v:any)=>void,numeric=true)=><View key={key} style={styles.field}><Text style={styles.text}>{label(key)}</Text><TextInput accessibilityLabel={label(key)} editable={!busy} style={styles.input} value={String(value)} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" onChangeText={v=>change(numeric?(v===''?'':Number(v)):v)}/></View>;
 if(rules?.engine==='company_rules_v1')return <ScrollView automaticallyAdjustKeyboardInsets keyboardDismissMode="on-drag" style={styles.screen} contentContainerStyle={{padding:18,paddingBottom:60}} keyboardShouldPersistTaps="handled"><Text style={styles.heading}>Worldwide company payroll rules</Text><Text style={styles.text}>Revision {revision}. New calculations only; existing records retain their snapshots.</Text>{!!notice&&<Text style={styles.warning}>{notice}</Text>}{button('Use Alberta reference template',()=>setRules(metadata.template))}<WorldwidePayrollRules rules={rules} setRules={setRules} metadata={metadata} busy={busy} preview={i=>void run(async()=>{const d:any=await api.post('/payroll-rules/preview',{rules,input:i});setResult(d.result);})}/>{field('Reason for change',reason,setReason,false)}{button('Save new revision',()=>void run(async()=>{await api.post('/payroll-rules',{rules,reason,expectedRevision:revision});await load();setNotice('Saved new revision.');}),reason.trim().length<8)}<Text style={styles.section}>History</Text>{history.map(h=><View key={h.revision}><Text style={styles.text}>{h.reason}</Text>{button('Load revision '+h.revision,()=>setRules(h.rules))}</View>)}{result&&<><Text style={styles.warning}>{result.classification}</Text><Text style={styles.text}>Gross: {result.gross} · Net: {result.net} {result.currency}</Text>{result.lines?.map((l:any)=><Text key={l.id} style={styles.text}>{l.label}: {l.amount} ({l.category})</Text>)}</>}</ScrollView>;
 return <ScrollView automaticallyAdjustKeyboardInsets keyboardDismissMode="on-drag" style={styles.screen} contentContainerStyle={{padding:18,paddingBottom:60}} keyboardShouldPersistTaps="handled"><Text style={styles.heading}>Company payroll rules</Text><Text style={styles.text}>Revision {revision}. New revisions affect new calculations only. Reviewed payroll retains its original calculation and rules.</Text><Text style={styles.warning}>Review required. The calculation engine currently covers Alberta/CAD regular wages in 2026 only. Custom edits do not establish tax compliance. No money is sent.</Text>{!!notice&&<Text accessibilityRole="alert" style={styles.warning}>{notice}</Text>}
 {rules&&<>{button('Configure worldwide company rules',()=>setRules(metadata.worldwideTemplate))}<Text style={styles.section}>Jurisdiction and effective dates</Text>{['country','subdivision','currency','effectiveFrom','effectiveTo'].map(k=>field(k,rules[k],v=>setRules({...rules,[k]:v}),false))}
 <Text style={styles.section}>Company policy</Text><Text style={styles.text}>Rates are decimals: 0.04 = 4%. Vacation rate previews accrual only; employee vacation settings still govern draft vacation pay. Overtime multiplier applies to new drafts.</Text>{Object.keys(rules.policy).map(k=>field(k,rules.policy[k],v=>setRules({...rules,policy:{...rules.policy,[k]:v}})))}
 <Text style={styles.section}>Statutory rules — advanced</Text><Text style={styles.text}>Use an independent payroll review before changing tax or contribution rules. Bracket formula: rate × annual income − constant.</Text>{Object.keys(rules.statutory).filter(k=>!k.endsWith('Brackets')).map(k=>field(k,rules.statutory[k],v=>setRules({...rules,statutory:{...rules.statutory,[k]:v}})))}
 {['federalBrackets','provincialBrackets'].map(k=><View key={k}><Text style={styles.section}>{label(k)}</Text>{rules.statutory[k].map((br:any,i:number)=><View key={i} style={styles.bracket}>{['floor','rate','constant'].map(f=>field(f,br[f],v=>setRules({...rules,statutory:{...rules.statutory,[k]:rules.statutory[k].map((r:any,j:number)=>j===i?{...r,[f]:v}:r)}})))}</View>)}</View>)}
 {field('Reason for change and review reference',reason,setReason,false)}{button('Save new revision',()=>void run(async()=>{await api.post('/payroll-rules',{rules,reason,expectedRevision:revision});await load();setNotice('Revision saved. Existing payroll was not recalculated.');}),reason.trim().length<8)}
 <Text style={styles.section}>History</Text>{history.map(h=><View key={h.revision}><Text style={styles.text}>Revision {h.revision}: {h.reason}</Text>{button('Load revision '+h.revision+' into editor',()=>{setRules(h.rules);setReason('Restore revision '+h.revision);})}</View>)}
 <Text style={styles.section}>Preview — no payroll changes</Text><Text style={styles.warning}>Regular cash wages, full-year CPP eligibility and standard EI only. Excludes bonuses, Quebec transfers, noncash benefits, pension/RRSP deductions and special credits. YTD amounts exclude this payment and must be independently checked.</Text>{Object.keys(input).filter(k=>k!=='standardCaseConfirmed').map(k=>field(k,input[k],v=>setInput({...input,[k]:v}),k!=='payDate'))}<Text style={styles.text}>I confirm this example meets these limits.</Text><Switch accessibilityLabel="Confirm standard calculation scope" value={input.standardCaseConfirmed} onValueChange={v=>setInput({...input,standardCaseConfirmed:v})}/>{button('Preview calculation',()=>void run(async()=>{const d:any=await api.post('/payroll-rules/preview',{rules,input});setResult(d.result);}),!input.standardCaseConfirmed)}{result&&<View><Text style={styles.warning}>{result.classification}. Not government-certified.</Text>{['gross','cpp','cpp2','ei','incomeTax','net','vacationAccrualEstimate'].map(k=><Text key={k} style={styles.text}>{label(k)}: {result[k]} {result.currency}</Text>)}</View>}
 </>}{button('Reload saved rules',()=>void run(load))}</ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#071321'},heading:{fontSize:25,fontWeight:'bold',color:'#fff',marginBottom:12},section:{fontSize:19,fontWeight:'bold',color:'#67E8F9',marginTop:22,marginBottom:10},text:{color:'#DAE5EE',lineHeight:22},warning:{color:'#FFDB91',backgroundColor:'#322B1B',padding:12,marginVertical:12,lineHeight:22},field:{marginVertical:7},input:{backgroundColor:'#132738',color:'#fff',padding:12,borderRadius:6,marginTop:4,borderWidth:1,borderColor:'#34506A'},button:{backgroundColor:'#67E8F9',padding:13,borderRadius:6,marginVertical:8},buttonText:{color:'#071321',fontWeight:'bold'},bracket:{borderBottomWidth:1,borderColor:'#34506A',paddingBottom:10}});
