import React,{useMemo,useState} from 'react';
import {Alert,ScrollView,Share,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {MaterialIcons} from '@expo/vector-icons';

type Tool={id:string;name:string;category:string;fields:string[];solve:(n:(i:number)=>number)=>string[]};
const fmt=(v:number,d=3)=>Number.isFinite(v)?Number(v.toFixed(d)).toLocaleString():'—';
const tools:Tool[]=[
 {id:'concrete',name:'Concrete quantity',category:'Construction',fields:['Length ft','Width ft','Depth in','Waste %'],solve:n=>{const y=n(0)*n(1)*n(2)/12/27*(1+n(3)/100);return [`${fmt(y)} yd³`,`${Math.ceil(y*45)} × 80 lb bags`]}},
 {id:'asphalt',name:'Asphalt tonnage',category:'Construction',fields:['Length ft','Width ft','Depth in','Density lb/ft³'],solve:n=>[`${fmt(n(0)*n(1)*n(2)/12*n(3)/2000)} US tons`]},
 {id:'spacing',name:'Equal spacing',category:'Carpentry',fields:['Clear span in','Item width in','Item count'],solve:n=>{const c=Math.max(1,Math.floor(n(2))),g=(n(0)-c*n(1))/(c+1);return [`Gap ${fmt(g)} in`,`On-center ${fmt(g+n(1))} in`]}},
 {id:'square',name:'Check square',category:'Carpentry',fields:['Side A','Side B'],solve:n=>[`Diagonal ${fmt(Math.hypot(n(0),n(1)))} same units`]},
 {id:'stairs',name:'Stair layout',category:'Carpentry',fields:['Total rise in','Target riser in','Tread depth in'],solve:n=>{const r=Math.max(1,Math.ceil(n(0)/n(1)));return [`${r} risers`,`Rise ${fmt(n(0)/r)} in`,`${Math.max(0,r-1)} treads`,`Run ${fmt((r-1)*n(2))} in`]}},
 {id:'roof',name:'Roof & slope',category:'Construction',fields:['Run ft','Rise ft','Building length ft'],solve:n=>{const r=Math.hypot(n(0),n(1));return [`Pitch ${fmt(n(1)/n(0)*12)}:12`,`Angle ${fmt(Math.atan2(n(1),n(0))*180/Math.PI)}°`,`Rafter ${fmt(r)} ft`,`Area ${fmt(2*r*n(2))} ft²`]}},
 {id:'board',name:'Board feet',category:'Carpentry',fields:['Thickness in','Width in','Length ft','Quantity'],solve:n=>[`${fmt(n(0)*n(1)*n(2)/12*n(3))} board ft`]},
 {id:'circle',name:'Circle & arc',category:'Measure',fields:['Diameter','Arc angle °'],solve:n=>[`Area ${fmt(Math.PI*n(0)*n(0)/4)}`,`Circumference ${fmt(Math.PI*n(0))}`,`Arc ${fmt(Math.PI*n(0)*n(1)/360)}`]},
 {id:'paint',name:'Paint & coverings',category:'Finishing',fields:['Perimeter ft','Height ft','Openings ft²','Coats'],solve:n=>{const a=Math.max(0,n(0)*n(1)-n(2));return [`Area ${fmt(a)} ft²`,`${Math.ceil(a*n(3)/350)} gal @ 350 ft²/gal`]}},
 {id:'ohm',name:"Ohm's law & power",category:'Electrical',fields:['Voltage V','Current A'],solve:n=>[`${fmt(n(0)/n(1))} Ω`,`${fmt(n(0)*n(1))} W`]},
 {id:'pipe',name:'Pipe volume & flow',category:'Plumbing',fields:['Inside diameter in','Length ft','Flow gal/min'],solve:n=>{const g=Math.PI*(n(0)/2)**2*n(1)*12/231;return [`${fmt(g)} US gal`,`Fill ${fmt(g/n(2))} min`]}},
 {id:'landscape',name:'Soil, mulch & gravel',category:'Landscaping',fields:['Length ft','Width ft','Depth in','Waste %'],solve:n=>[`${fmt(n(0)*n(1)*n(2)/12/27*(1+n(3)/100))} yd³`]},
 {id:'dilution',name:'Chemical dilution',category:'Facilities',fields:['Finished volume L','Water parts'],solve:n=>[`${fmt(n(0)/(n(1)+1))} L concentrate`,`${fmt(n(0)*n(1)/(n(1)+1))} L water`]},
 {id:'fuel',name:'Mileage & fuel',category:'Logistics',fields:['Distance km','L/100km','Price/L'],solve:n=>{const l=n(0)*n(1)/100;return [`${fmt(l)} L`,`$${fmt(l*n(2),2)}`]}}
 ,{id:'slab',name:'Concrete slab',category:'Concrete',fields:['Length ft','Width ft','Thickness in','Waste %','Truck capacity yd³','Cost/yd³'],solve:n=>{const a=n(0)*n(1),y=a*n(2)/12/27*(1+n(3)/100);return [`Area ${fmt(a)} ft²`,`${fmt(y)} yd³`,`${Math.ceil(y*45)} × 80 lb bags`,`${Math.ceil(y/Math.max(n(4),.001))} truckloads`,`$${fmt(y*n(5),2)}`]}}
 ,{id:'slope',name:'Slope & grade',category:'Sitework',fields:['Rise ft','Horizontal run ft'],solve:n=>{const rise=n(0),run=n(1);return [run>0?`Grade ${fmt(rise/run*100)}%`:'Grade —',run>0?`Angle ${fmt(Math.atan2(rise,run)*180/Math.PI)}°`:'Angle —',rise!==0?`Ratio 1:${fmt(run/Math.abs(rise))}`:'Level',run>0?`Pitch ${fmt(rise/run*12)}:12`:'Pitch —',`Slope ${fmt(Math.hypot(rise,run))} ft`]}}
 ,{id:'footing',name:'Continuous footing',category:'Concrete',fields:['Total length ft','Width in','Depth in','Waste %'],solve:n=>{const y=n(0)*n(1)/12*n(2)/12/27*(1+n(3)/100);return [`${fmt(y)} yd³`,`${Math.ceil(y*45)} × 80 lb bags`]}}
 ,{id:'pier',name:'Concrete pier & column',category:'Concrete',fields:['Diameter in','Depth/height ft','Quantity','Waste %'],solve:n=>{const y=Math.PI*(n(0)/24)**2*n(1)*n(2)/27*(1+n(3)/100);return [`${fmt(y)} yd³`,`${Math.ceil(y*45)} × 80 lb bags`]}}
 ,{id:'rebar',name:'Rebar grid',category:'Concrete',fields:['Slab length ft','Slab width ft','Spacing in','Lap/waste %','Weight lb/ft'],solve:n=>{const s=Math.max(n(2)/12,.001),a=Math.ceil(n(1)/s)+1,b=Math.ceil(n(0)/s)+1,total=(a*n(0)+b*n(1))*(1+n(3)/100);return [`${a} lengthwise bars`,`${b} crosswise bars`,`${fmt(total)} ft total`,`${fmt(total*n(4))} lb`]}}
 ,{id:'masonry',name:'Block, brick & mortar',category:'Masonry',fields:['Wall length ft','Wall height ft','Openings ft²','Unit face area in²','Waste %'],solve:n=>{const a=Math.max(0,n(0)*n(1)-n(2)),c=Math.ceil(a*144/Math.max(n(3),.001)*(1+n(4)/100));return [`${fmt(a)} ft²`,`${c} units`,`${fmt(c*.025)} ft³ mortar allowance`]}}
 ,{id:'excavation',name:'Excavation & backfill',category:'Sitework',fields:['Length ft','Width ft','Depth ft','Swell %','Structure yd³'],solve:n=>{const b=n(0)*n(1)*n(2)/27;return [`${fmt(b)} yd³ bank`,`${fmt(b*(1+n(3)/100))} yd³ loose`,`${fmt(Math.max(0,b-n(4)))} yd³ backfill`]}}
 ,{id:'trench',name:'Trench volume',category:'Sitework',fields:['Length ft','Width in','Depth in','Bedding in'],solve:n=>{const y=n(0)*n(1)/12*n(2)/12/27,b=n(0)*n(1)/12*n(3)/12/27;return [`${fmt(y)} yd³ excavation`,`${fmt(b)} yd³ bedding`,`${fmt(Math.max(0,y-b))} yd³ spoil`]}}
 ,{id:'drywall',name:'Drywall materials',category:'Finishing',fields:['Surface area ft²','Sheet area ft²','Waste %'],solve:n=>{const a=n(0)*(1+n(2)/100),s=Math.ceil(a/Math.max(n(1),.001));return [`${fmt(a)} ft² adjusted`,`${s} sheets`,`${s*32} screws`,`${Math.ceil(s/10)} compound pails`]}}
 ,{id:'tile',name:'Tile & flooring',category:'Finishing',fields:['Length ft','Width ft','Waste %','Coverage/carton ft²','Cost/ft²'],solve:n=>{const a=n(0)*n(1),buy=a*(1+n(2)/100);return [`${fmt(a)} ft² room`,`${fmt(buy)} ft² purchase`,`${Math.ceil(buy/Math.max(n(3),.001))} cartons`,`$${fmt(buy*n(4),2)}`]}}
 ,{id:'roofing',name:'Roofing materials',category:'Roofing',fields:['Plan length ft','Plan width ft','Pitch rise in/12','Waste %'],solve:n=>{const a=n(0)*n(1)*Math.sqrt(1+(n(2)/12)**2)*(1+n(3)/100),sq=a/100;return [`${fmt(a)} ft²`,`${fmt(sq)} squares`,`${Math.ceil(sq*3)} bundles`,`${Math.ceil(a/400)} underlayment rolls`]}}
 ,{id:'deck',name:'Deck boards & joists',category:'Carpentry',fields:['Deck length ft','Deck width ft','Board face in','Gap in','Joist spacing in','Waste %'],solve:n=>{const rows=Math.ceil(n(1)*12/Math.max(n(2)+n(3),.001)),linear=rows*n(0)*(1+n(5)/100);return [`${rows} board rows`,`${fmt(linear)} linear ft`,`${Math.ceil(n(0)*12/Math.max(n(4),.001))+1} joists`]}}
 ,{id:'fence',name:'Fence materials',category:'Carpentry',fields:['Fence length ft','Section length ft','Rails/section','Picket plus gap in'],solve:n=>{const s=Math.ceil(n(0)/Math.max(n(1),.001));return [`${s} sections`,`${s+1} posts`,`${s*n(2)} rails`,`${Math.ceil(n(0)*12/Math.max(n(3),.001))} pickets`]}}
 ,{id:'insulation',name:'Insulation',category:'Finishing',fields:['Wall length ft','Wall height ft','Openings ft²','Coverage/package ft²','Waste %','Cost/package'],solve:n=>{const a=Math.max(0,n(0)*n(1)-n(2))*(1+n(4)/100),p=Math.ceil(a/Math.max(n(3),.001));return [`${fmt(a)} ft²`,`${p} packages`,`$${fmt(p*n(5),2)}`]}}
 ,{id:'voltage-drop',name:'Voltage drop',category:'Electrical',fields:['System voltage V','Current A','One-way length ft','Resistance Ω/1000ft'],solve:n=>{const d=2*n(2)*n(1)*n(3)/1000;return [`${fmt(d)} V drop`,n(0)>0?`${fmt(d/n(0)*100)}% drop`:'—',`${fmt(n(0)-d)} V load`]}}
 ,{id:'hvac-airflow',name:'HVAC airflow',category:'HVAC',fields:['Room length ft','Room width ft','Room height ft','Air changes/hour'],solve:n=>{const v=n(0)*n(1)*n(2);return [`${fmt(v)} ft³`,`${fmt(v*n(3)/60)} CFM`]}}
 ,{id:'equipment-cost',name:'Equipment operating cost',category:'Logistics',fields:['Operating hours','Fuel L/h','Fuel price/L','Rental/hour','Labour/hour'],solve:n=>{const fuel=n(0)*n(1)*n(2),rent=n(0)*n(3),lab=n(0)*n(4);return [`Fuel $${fmt(fuel,2)}`,`Rental $${fmt(rent,2)}`,`Labour $${fmt(lab,2)}`,`Total $${fmt(fuel+rent+lab,2)}`]}}
];
const parseFeet=(s:string)=>{const m=s.trim().match(/^(-?\d+)(?:\s*['′])?\s*(?:(\d+))?\s*(?:(\d+)\/(\d+))?/);if(!m)throw Error('Use 5\' 7 1/4');return Number(m[1])*12+Number(m[2]||0)+(m[3]?Number(m[3])/Number(m[4]):0)};
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;
const inchFraction=(x:number,p:number)=>{const w=Math.floor(Math.abs(x)),num=Math.round((Math.abs(x)-w)*p);if(!num)return `${x<0?'-':''}${w}`;const g=gcd(num,p);return `${x<0?'-':''}${w?`${w} `:''}${num/g}/${p/g}`};

export default function WorkerToolsScreen({navigation}:any){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<Tool|null>(null),[values,setValues]=useState<string[]>([]),[results,setResults]=useState<string[]>([]),[measure,setMeasure]=useState("5' 7 1/4"),[precision,setPrecision]=useState(16),[tape,setTape]=useState<string[]>([]);
 const list=useMemo(()=>tools.filter(t=>(t.name+t.category).toLowerCase().includes(query.toLowerCase())),[query]);
 const saveTape=async(next:string[])=>{setTape(next);await AsyncStorage.setItem('workerTools:tape',JSON.stringify(next.slice(0,100)))};
 const calculate=()=>{if(!selected)return;const out=selected.solve(i=>Number(values[i]||0));setResults(out);void saveTape([`${selected.name}: ${out.join(', ')}`,...tape])};
 const measureNow=()=>{try{const inches=parseFeet(measure),ft=Math.trunc(inches/12),rem=inches-ft*12,line=`${ft}' ${inchFraction(rem,precision)}\" = ${fmt(inches*.0254,4)} m`;setResults([line]);void saveTape([line,...tape])}catch(e){Alert.alert('Check measurement',(e as Error).message)}};
 return <View style={s.root}><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><MaterialIcons name="arrow-back" size={25} color="#DDF7FF"/></TouchableOpacity><View><Text style={s.title}>Worker Tools</Text><Text style={s.sub}>Offline field calculators</Text></View></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.hero}><MaterialIcons name="engineering" size={34} color="#67E8F9"/><Text style={s.heroTitle}>Built for work beyond a desk</Text><Text style={s.body}>Construction, carpentry, electrical, plumbing, landscaping, facilities and logistics tools.</Text></View>
  <TextInput style={s.input} placeholder="Search tools" placeholderTextColor="#6F8293" value={query} onChangeText={setQuery}/>
  <View style={s.grid}>{list.map(t=><TouchableOpacity key={t.id} style={[s.card,selected?.id===t.id&&s.cardActive]} onPress={()=>{setSelected(t);setValues(t.fields.map(()=>''));setResults([])}}><Text style={s.category}>{t.category.toUpperCase()}</Text><Text style={s.cardTitle}>{t.name}</Text></TouchableOpacity>)}</View>
  {selected&&<View style={s.panel}><Text style={s.panelTitle}>{selected.name}</Text>{selected.fields.map((f,i)=><TextInput key={f} style={s.input} placeholder={f} placeholderTextColor="#6F8293" keyboardType="decimal-pad" value={values[i]} onChangeText={x=>setValues(v=>v.map((a,j)=>j===i?x:a))}/>)}<TouchableOpacity style={s.primary} onPress={calculate}><Text style={s.primaryText}>CALCULATE</Text></TouchableOpacity>{results.map(x=><Text key={x} style={s.result}>{x}</Text>)}</View>}
  <View style={s.panel}><Text style={s.panelTitle}>Measure Master</Text><Text style={s.body}>Feet-inch-fractions, metric output, 1/2 through 1/64 precision and paperless tape.</Text><TextInput style={s.input} value={measure} onChangeText={setMeasure} placeholder="5' 7 1/4" placeholderTextColor="#6F8293"/><View style={s.row}>{[2,4,8,16,32,64].map(p=><TouchableOpacity key={p} style={[s.pill,precision===p&&s.pillOn]} onPress={()=>setPrecision(p)}><Text style={s.pillText}>1/{p}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.primary} onPress={measureNow}><Text style={s.primaryText}>CONVERT MEASUREMENT</Text></TouchableOpacity></View>
  <View style={s.panel}><View style={s.between}><Text style={s.panelTitle}>Paperless tape</Text><TouchableOpacity onPress={()=>Share.share({message:tape.join('\n')})}><MaterialIcons name="share" size={22} color="#67E8F9"/></TouchableOpacity></View>{tape.slice(0,20).map((x,i)=><Text key={`${i}-${x}`} style={s.tape}>{x}</Text>)}{tape.length===0&&<Text style={s.body}>Saved results appear here.</Text>}</View>
  <TouchableOpacity style={s.project} onPress={()=>navigation.navigate('Folders')}><MaterialIcons name="folder-open" size={24} color="#67E8F9"/><View><Text style={s.cardTitle}>Project documents & field evidence</Text><Text style={s.body}>Open project drawings, photos and captured evidence.</Text></View></TouchableOpacity>
  <Text style={s.disclaimer}>Estimates only. Verify regulated, structural, electrical and safety-critical work against local requirements.</Text>
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050B12'},header:{paddingTop:52,paddingHorizontal:18,paddingBottom:15,flexDirection:'row',gap:14,alignItems:'center',borderBottomWidth:1,borderBottomColor:'#172A3C'},title:{color:'#F5FBFF',fontSize:22,fontWeight:'900'},sub:{color:'#7F93A6',fontSize:12},content:{padding:16,paddingBottom:50},hero:{backgroundColor:'#0B1724',padding:20,borderRadius:20,borderWidth:1,borderColor:'#1C3850',marginBottom:14},heroTitle:{color:'#F3FAFF',fontSize:20,fontWeight:'900',marginTop:8},body:{color:'#8EA2B5',fontSize:12,lineHeight:18},input:{backgroundColor:'#09131D',color:'#F4FAFF',borderWidth:1,borderColor:'#1B3348',borderRadius:12,padding:13,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},card:{width:'48%',minHeight:86,backgroundColor:'#09131D',borderWidth:1,borderColor:'#172A3C',borderRadius:15,padding:13},cardActive:{borderColor:'#67E8F9',backgroundColor:'#0D202D'},category:{color:'#67E8F9',fontSize:8,fontWeight:'900',letterSpacing:1},cardTitle:{color:'#E8F3F8',fontSize:13,fontWeight:'800',marginTop:7},panel:{backgroundColor:'#0B1724',borderRadius:18,borderWidth:1,borderColor:'#1C3850',padding:16,marginTop:16},panelTitle:{color:'#F4FAFF',fontSize:18,fontWeight:'900',marginBottom:12},primary:{backgroundColor:'#67E8F9',padding:14,borderRadius:12,alignItems:'center',marginTop:4},primaryText:{color:'#06101D',fontWeight:'900'},result:{color:'#A7F3D0',fontSize:17,fontWeight:'800',marginTop:12},row:{flexDirection:'row',flexWrap:'wrap',gap:6,marginBottom:10},pill:{paddingVertical:7,paddingHorizontal:10,borderRadius:20,borderWidth:1,borderColor:'#2B4053'},pillOn:{backgroundColor:'#155E75',borderColor:'#67E8F9'},pillText:{color:'#DDF7FF',fontSize:11},between:{flexDirection:'row',justifyContent:'space-between'},tape:{color:'#C9D8E4',fontFamily:'monospace',fontSize:11,paddingVertical:7,borderBottomWidth:1,borderBottomColor:'#172A3C'},project:{flexDirection:'row',gap:12,backgroundColor:'#0B1724',padding:16,borderRadius:16,borderWidth:1,borderColor:'#1C3850',marginTop:16},disclaimer:{color:'#687A8B',fontSize:10,lineHeight:15,marginTop:18}});
