import React,{useState} from 'react';
import {View,Text,TextInput,TouchableOpacity,Switch,StyleSheet} from 'react-native';
const label=(s:string)=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ');
const line=()=>({id:'line_'+Date.now(),label:'New deduction',category:'other_deduction',method:'manual',basis:'gross',period:'pay_period',amount:0,rate:0,exemption:0,credit:0,annualCap:null,brackets:[{above:0,rate:0}]});
export default function WorldwidePayrollRules({rules,setRules,metadata,preview,busy}:{rules:any;setRules:(v:any)=>void;metadata:any;preview:(i:any)=>void;busy:boolean}){
 const [input,setInput]=useState<any>(null);
 const field=(k:string,v:any,change:(v:any)=>void,numeric=false)=><View key={k} style={{marginVertical:6}}><Text style={s.text}>{label(k)}</Text><TextInput accessibilityLabel={label(k)} editable={!busy} style={s.input} value={String(v??'')} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" onChangeText={v=>change(numeric?(v===''?'':Number(v)):v)}/></View>;
 const button=(title:string,fn:()=>void)=><TouchableOpacity disabled={busy} accessibilityRole="button" style={s.button} onPress={fn}><Text style={s.buttonText}>{title}</Text></TouchableOpacity>;
 const update=(index:number,k:string,v:any)=>{setRules({...rules,lines:rules.lines.map((l:any,i:number)=>i===index?{...l,[k]:v}:l)});setInput(null);};
 return <View><Text style={s.warning}>Worldwide company-configured mode. No local tax rates are prefilled or certified. Independently review rules, inputs, deductions and rounding. Country selection is not verified tax coverage.</Text>
 {field('country',rules.country,v=>setRules({...rules,country:v.toUpperCase()}))}<Text style={s.text}>{metadata.countries.find((c:any)=>c.code===rules.country)?.name||'Enter an ISO country code, such as US, GB, AU, IN, DE, JP or CA.'}</Text>
 {field('subdivision',rules.subdivision,v=>setRules({...rules,subdivision:v}))}
 {field('currency',rules.currency,v=>setRules({...rules,currency:v.toUpperCase()}))}<Text style={s.text}>{metadata.currencies.find((c:any)=>c.code===rules.currency)?`${rules.currency}: ${metadata.currencies.find((c:any)=>c.code===rules.currency).decimals} decimal places`:'Enter a supported currency code, e.g. USD, GBP, EUR, JPY, INR or CAD.'}</Text>
 {['effectiveFrom','effectiveTo'].map(k=>field(k,rules[k],v=>setRules({...rules,[k]:v})))}
 <Text style={s.heading}>Company policy</Text>{Object.keys(rules.policy).map(k=>field(k,rules.policy[k],v=>setRules({...rules,policy:{...rules.policy,[k]:v}}),true))}<Text style={s.text}>Rates are decimals (0.04 = 4%). Vacation is a preview accrual only.</Text>
 <Text style={s.heading}>Deductions and employer costs</Text><Text style={s.text}>Lines calculate independently. Annualized formulas multiply the basis by pay periods, apply the formula and divide by pay periods. Exemption is in that period; credit is per payment. Caps require YTD contributions. Manual amounts are final reviewed amounts.</Text>
 {rules.lines.map((l:any,index:number)=><View key={index} style={s.card}>{field('id',l.id,v=>update(index,'id',v))}{field('label',l.label,v=>update(index,'label',v))}
 {Object.entries({category:['tax','employee_contribution','other_deduction','employer_contribution'],method:['manual','fixed','percentage','progressive'],basis:['gross','taxable'],period:['pay_period','annualized']}).map(([k,options])=><View key={k}><Text style={s.heading}>{label(k)}: {label(l[k])}</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{options.map(o=><TouchableOpacity accessibilityRole="button" key={o} style={[s.choice,l[k]===o&&{borderColor:'#67E8F9'}]} onPress={()=>{if(k==='method'&&o==='manual'){setRules({...rules,lines:rules.lines.map((x:any,i:number)=>i===index?{...x,method:o,annualCap:null,exemption:0,credit:0}:x)});setInput(null);}else update(index,k,o);}}><Text style={s.text}>{label(o)}</Text></TouchableOpacity>)}</View></View>)}
 {l.method!=='manual'&&<>{l.method==='fixed'&&field('amount',l.amount,v=>update(index,'amount',v),true)}{l.method==='percentage'&&field('rate',l.rate,v=>update(index,'rate',v),true)}{['exemption','credit'].map(k=>field(k,l[k],v=>update(index,k,v),true))}{field('annualCap (blank = none)',l.annualCap,v=>update(index,'annualCap',v===''?null:v),true)}</>}
 {l.method==='progressive'&&<><Text style={s.text}>Marginal tax brackets (rate applies only to each slice).</Text>{l.brackets.map((b:any,j:number)=><View key={j}>{['above','rate'].map(k=>field(k,b[k],v=>update(index,'brackets',l.brackets.map((x:any,n:number)=>n===j?{...x,[k]:v}:x)),true))}{j>0&&button('Remove bracket',()=>update(index,'brackets',l.brackets.filter((_:any,n:number)=>n!==j)))}</View>)}{button('Add bracket',()=>update(index,'brackets',[...l.brackets,{above:Number(l.brackets[l.brackets.length-1].above)+10000,rate:0}]))}</>}
 {rules.lines.length>1&&button('Remove line',()=>{setRules({...rules,lines:rules.lines.filter((_:any,i:number)=>i!==index)});setInput(null);})}</View>)}{button('Add line',()=>{setRules({...rules,lines:[...rules.lines,line()]});setInput(null);})}
 <Text style={s.heading}>Local payroll rules review</Text>{['reviewer','reference','reviewedOn'].map(k=>field(k,rules.review[k],v=>setRules({...rules,review:{...rules.review,[k]:v}})))}<Text style={s.text}>The named reviewer checked this complete rule set. Company attestation does not certify the software.</Text><Switch accessibilityLabel="Confirm local rule review" value={rules.review.confirmed} onValueChange={v=>setRules({...rules,review:{...rules.review,confirmed:v}})}/>
 {button('Prepare preview',()=>setInput({payDate:new Date().toISOString().slice(0,10),gross:0,taxable:0,manualAmounts:Object.fromEntries(rules.lines.filter((l:any)=>l.method==='manual').map((l:any)=>[l.id,''])),ytd:Object.fromEntries(rules.lines.filter((l:any)=>l.annualCap!==null).map((l:any)=>[l.id,''])),reviewReference:'',companyRulesConfirmed:false}))}
 {input&&<><Text style={s.warning}>Supply gross and taxable pay independently. No implicit deduction ordering, country tax calculation, filing or bank payment.</Text>{['payDate','gross','taxable','reviewReference'].map(k=>field(k,input[k],v=>setInput({...input,[k]:v}),['gross','taxable'].includes(k)))}{rules.lines.filter((l:any)=>l.method==='manual').map((l:any)=>field('Reviewed amount: '+l.label,input.manualAmounts[l.id],v=>setInput({...input,manualAmounts:{...input.manualAmounts,[l.id]:v}}),true))}{rules.lines.filter((l:any)=>l.annualCap!==null).map((l:any)=>field('YTD contribution: '+l.label,input.ytd[l.id],v=>setInput({...input,ytd:{...input.ytd,[l.id]:v}}),true))}<Text style={s.text}>I independently checked these local payroll inputs and rules.</Text><Switch accessibilityLabel="Confirm preview inputs" value={input.companyRulesConfirmed} onValueChange={v=>setInput({...input,companyRulesConfirmed:v})}/>{input.companyRulesConfirmed&&button('Calculate preview',()=>preview(input))}</>}
 </View>;
}
const s=StyleSheet.create({text:{color:'#DFEAF4',lineHeight:22},heading:{color:'#67E8F9',fontSize:17,fontWeight:'bold',marginTop:18},warning:{color:'#FFD991',padding:12,backgroundColor:'#332B18',lineHeight:22,marginVertical:12},input:{color:'#fff',backgroundColor:'#132738',padding:12,borderWidth:1,borderColor:'#34506A',borderRadius:6},button:{backgroundColor:'#67E8F9',padding:12,borderRadius:6,marginVertical:8},buttonText:{color:'#071321',fontWeight:'bold'},card:{padding:12,borderWidth:1,borderColor:'#34506A',marginVertical:10},choice:{borderWidth:1,borderColor:'#34506A',borderRadius:5,padding:9,margin:3}});
