import express,{Request,Response} from 'express';
import {verifyToken} from '../utils/auth';
import {pool} from '../config/database';
import {buildEvidenceZip,evidenceOptions} from '../services/evidenceBundleService';
import {generateGpsTrailVideo,generateTimeEntryPdf,generateVoiceCaptionVideo} from '../services/evidenceMediaService';
const router=express.Router();
async function actor(req:Request){const d=verifyToken(req);const r=await pool.query('SELECT id,company_id,role FROM users WHERE id=$1',[d.id]);if(!r.rowCount||!r.rows[0].company_id)throw new Error('Not authenticated');return{id:String(r.rows[0].id),companyId:String(r.rows[0].company_id),role:String(r.rows[0].role||'')}}
router.get('/recent',async(req,res)=>{try{const a=await actor(req);const r=await pool.query(`SELECT te.id,te.clock_in,te.clock_out,concat_ws(' ',u.first_name,u.last_name) employee_name,p.name project_name,(SELECT count(*) FROM photos ph WHERE ph.time_entry_id=te.id) media_count,(SELECT count(*) FROM voice_notes vn WHERE vn.time_entry_id=te.id) voice_count,(SELECT count(*) FROM gps_tracking g WHERE g.time_entry_id=te.id) gps_count FROM time_entries te JOIN users u ON u.id=te.user_id LEFT JOIN projects p ON p.id=te.project_id WHERE u.company_id=$1 ORDER BY te.clock_in DESC LIMIT 100`,[a.companyId]);res.json({success:true,entries:r.rows});}catch(e:any){res.status(401).json({success:false,message:e.message});}});
router.get('/time-entry/:id',async(req,res)=>{try{const a=await actor(req);res.json({success:true,...await evidenceOptions(a.companyId,String(req.params.id))});}catch(e:any){res.status(/authenticated/i.test(e.message)?401:404).json({success:false,message:e.message});}});
const sendArtifact=(res:Response,artifact:{buffer:Buffer;fileName:string;mimeType:string;verificationHash:string})=>{res.setHeader('Content-Type',artifact.mimeType);res.setHeader('Content-Disposition',`attachment; filename="${artifact.fileName}"`);res.setHeader('X-Evidence-SHA256',artifact.verificationHash);res.send(artifact.buffer)};
const requireManager=(role:string)=>{if(!['boss','manager','admin'].includes(role))throw new Error('Manager access is required to generate evidence')};
router.get('/time-entry/:id/gps-video',async(req,res)=>{try{const a=await actor(req);requireManager(a.role);sendArtifact(res,await generateGpsTrailVideo(a.companyId,String(req.params.id)));}catch(e:any){res.status(/manager access/i.test(e.message)?403:400).json({success:false,message:e.message});}});
router.get('/time-entry/:id/time-entry-pdf',async(req,res)=>{try{const a=await actor(req);requireManager(a.role);sendArtifact(res,await generateTimeEntryPdf(a.companyId,String(req.params.id)));}catch(e:any){res.status(/manager access/i.test(e.message)?403:400).json({success:false,message:e.message});}});
router.get('/voice-note/:id/caption-video',async(req,res)=>{try{const a=await actor(req);requireManager(a.role);sendArtifact(res,await generateVoiceCaptionVideo(a.companyId,String(req.params.id)));}catch(e:any){res.status(/manager access/i.test(e.message)?403:400).json({success:false,message:e.message});}});
router.post('/time-entry/:id/download',async(req:Request,res:Response)=>{try{const a=await actor(req);if(!['boss','manager','admin'].includes(a.role))return res.status(403).json({success:false,message:'Manager access is required to generate evidence'});const result=await buildEvidenceZip(a.companyId,a.id,String(req.params.id),req.body||{});res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="${result.fileName}"`);res.setHeader('X-Evidence-SHA256',result.hash);res.send(result.buffer);}catch(e:any){console.error('Evidence package failed',e);res.status(400).json({success:false,message:e.message});}});
export default router;
