import express, { Request } from 'express';
import { pool } from '../config/database';
import { verifyToken } from '../utils/auth';

const router=express.Router();
type Actor={id:string;companyId:string;role:string};
async function manager(req:Request):Promise<Actor>{const token=verifyToken(req);const result=await pool.query('SELECT id,company_id,role FROM users WHERE id=$1',[token.id]);const row=result.rows[0];if(!row?.company_id)throw new Error('Not authenticated');if(!['boss','manager','admin'].includes(String(row.role).toLowerCase()))throw new Error('Payroll manager access is required');return{id:String(row.id),companyId:String(row.company_id),role:String(row.role)};}
const status=(message:string)=>/access|required/i.test(message)?403:400;

router.get('/company',async(req,res)=>{try{const a=await manager(req);const result=await pool.query(`SELECT id,name,legal_name,business_number,payroll_account_number,address,city,province,postal_code,phone,email,logo_url FROM companies WHERE id=$1`,[a.companyId]);res.json({success:true,company:result.rows[0]});}catch(e:any){res.status(status(e.message)).json({success:false,message:e.message});}});
router.patch('/company',async(req,res)=>{try{const a=await manager(req);const b=req.body;const result=await pool.query(`UPDATE companies SET name=COALESCE(NULLIF($1,''),name),legal_name=NULLIF($2,''),business_number=NULLIF($3,''),payroll_account_number=NULLIF($4,''),address=NULLIF($5,''),city=NULLIF($6,''),province=NULLIF($7,''),postal_code=NULLIF($8,''),phone=NULLIF($9,''),email=NULLIF($10,'') WHERE id=$11 RETURNING id,name,legal_name,business_number,payroll_account_number,address,city,province,postal_code,phone,email`,[b.name,b.legalName,b.businessNumber,b.payrollAccountNumber,b.address,b.city,String(b.province||'').toUpperCase(),b.postalCode,b.phone,b.email,a.companyId]);res.json({success:true,company:result.rows[0]});}catch(e:any){res.status(status(e.message)).json({success:false,message:e.message});}});

router.get('/vacation-policies',async(req,res)=>{try{const a=await manager(req);const result=await pool.query(`SELECT id,first_name,last_name,email,COALESCE(vacation_pay_rate,4) vacation_pay_rate,COALESCE(vacation_pay_method,'accrue') vacation_pay_method,COALESCE(vacation_pay_balance,0) vacation_pay_balance,COALESCE(vacation_hours_balance,0) vacation_hours_balance FROM users WHERE company_id=$1 AND LOWER(COALESCE(role,'employee'))<>'boss' ORDER BY first_name,last_name`,[a.companyId]);res.json({success:true,employees:result.rows});}catch(e:any){res.status(status(e.message)).json({success:false,message:e.message});}});
router.patch('/employees/:id/vacation',async(req,res)=>{try{const a=await manager(req),id=String(req.params.id),rate=Number(req.body.rate),method=String(req.body.method||'accrue'),payBalance=Number(req.body.payBalance||0),hoursBalance=Number(req.body.hoursBalance||0);if(!Number.isFinite(rate)||rate<0||rate>20)throw new Error('Vacation rate must be between 0 and 20 percent');if(!['accrue','each_pay'].includes(method))throw new Error('Vacation method must be accrue or each_pay');if(payBalance<0||hoursBalance<0)throw new Error('Vacation balances cannot be negative');const result=await pool.query(`UPDATE users SET vacation_pay_rate=$1,vacation_pay_method=$2,vacation_pay_balance=$3,vacation_hours_balance=$4,updated_at=NOW() WHERE id=$5 AND company_id=$6 RETURNING id`,[rate,method,payBalance,hoursBalance,id,a.companyId]);if(!result.rowCount)throw new Error('Employee not found in your company');res.json({success:true});}catch(e:any){res.status(status(e.message)).json({success:false,message:e.message});}});

router.patch('/time-entries/:id',async(req,res)=>{const client=await pool.connect();try{const a=await manager(req),id=String(req.params.id),reason=String(req.body.reason||'').trim();if(reason.length<5)throw new Error('A correction reason of at least 5 characters is required');await client.query('BEGIN');const current=await client.query(`SELECT te.* FROM time_entries te JOIN users u ON u.id=te.user_id WHERE te.id=$1 AND u.company_id=$2 FOR UPDATE`,[id,a.companyId]);if(!current.rowCount)throw new Error('Time entry not found in your company');const before=current.rows[0];if(before.payroll_locked_at)throw new Error('This entry is locked by payroll and cannot be edited');const clockIn=new Date(req.body.clockIn),clockOut=new Date(req.body.clockOut);const breakMinutes=Number(req.body.breakMinutes||0);if(!Number.isFinite(clockIn.getTime())||!Number.isFinite(clockOut.getTime())||clockOut<=clockIn)throw new Error('Clock-out must be after clock-in');if(breakMinutes<0)throw new Error('Break minutes cannot be negative');const hours=Math.max(0,(clockOut.getTime()-clockIn.getTime())/3600000-breakMinutes/60);const rateResult=await client.query(`SELECT hourly_rate FROM compensation_history WHERE user_id=$1 AND effective_date<=$2::date ORDER BY effective_date DESC LIMIT 1`,[before.user_id,clockIn.toISOString()]);const rate=Number(rateResult.rows[0]?.hourly_rate||0);const regular=Math.min(hours,8),overtime=Math.max(hours-8,0),wage=regular*rate+overtime*rate*1.5;const updated=await client.query(`UPDATE time_entries SET clock_in=$1,clock_out=$2,break_minutes=$3,regular_hours=$4,overtime_hours=$5,total_wage=$6,approval_status='needs_review',correction_reason=$7,corrected_by=$8,corrected_at=NOW() WHERE id=$9 RETURNING *`,[clockIn,clockOut,breakMinutes,regular,overtime,wage,reason,a.id,id]);await client.query(`INSERT INTO time_entry_audit_logs(company_id,time_entry_id,actor_id,action,before_values,after_values,reason) VALUES($1,$2,$3,'corrected',$4,$5,$6)`,[a.companyId,id,a.id,JSON.stringify({clockIn:before.clock_in,clockOut:before.clock_out,breakMinutes:before.break_minutes}),JSON.stringify({clockIn,clockOut,breakMinutes,regularHours:regular,overtimeHours:overtime,totalWage:wage}),reason]);await client.query('COMMIT');res.json({success:true,entry:updated.rows[0]});}catch(e:any){await client.query('ROLLBACK');res.status(status(e.message)).json({success:false,message:e.message});}finally{client.release();}});
router.post('/time-entries/:id/approve',async(req,res)=>{const client=await pool.connect();try{const a=await manager(req),id=String(req.params.id);await client.query('BEGIN');const result=await client.query(`UPDATE time_entries te SET approval_status='approved',approved_by=$1,approved_at=NOW() FROM users u WHERE te.user_id=u.id AND te.id=$2 AND u.company_id=$3 AND te.clock_out IS NOT NULL AND te.payroll_locked_at IS NULL RETURNING te.id`,[a.id,id,a.companyId]);if(!result.rowCount)throw new Error('Completed, unlocked time entry not found');await client.query(`INSERT INTO time_entry_audit_logs(company_id,time_entry_id,actor_id,action) VALUES($1,$2,$3,'approved')`,[a.companyId,id,a.id]);await client.query('COMMIT');res.json({success:true});}catch(e:any){await client.query('ROLLBACK');res.status(status(e.message)).json({success:false,message:e.message});}finally{client.release();}});
export default router;
