import React,{useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,LinearProgress,MenuItem,Paper,Stack,TextField,Typography} from '@mui/material';
import {AutoAwesome,ArrowForward,Refresh,CalendarMonth,Groups,TaskAlt,ReceiptLong,MapOutlined} from '@mui/icons-material';
import {api} from '../services/api';

type Section={status:string;rows:any[];message?:string};
type Overview={company:any;manager:boolean;sections:Record<string,Section>;payPeriod:any;periodError:string|null;generatedAt:string;localDate:string;limits:Record<string,number>};
const Panel=({children,...props}:any)=><Paper variant="outlined" {...props} sx={{p:{xs:2,md:3},borderRadius:4,borderColor:'divider',backgroundImage:'none',...props.sx}}>{children}</Paper>;
export default function CommandCenter(){
 const nav=useNavigate();const[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[calendar,setCalendar]=useState(false);
 const[settings,setSettings]=useState({schedule:'weekly',timezone:'UTC',anchor:'',weekStart:1});
 const load=async()=>{setLoading(true);setError('');try{const next=await api.get<Overview>('/api/command-center/overview');setData(next);setSettings({schedule:next.company.schedule,timezone:next.company.timezone,anchor:next.company.anchor||'',weekStart:next.company.week_start});}catch(e:any){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const ask=(prompt:string)=>window.dispatchEvent(new CustomEvent('open-lucy',{detail:prompt}));
 const save=async()=>{setError('');try{await api.put('/api/command-center/calendar',settings);setCalendar(false);await load();}catch(e:any){setError(e.message);}};
 const rows=(key:string)=>data?.sections[key]?.rows||[];
 const count=(key:string)=>data?.sections[key]?.status==='ready'?`${rows(key).length}${rows(key).length===data.limits[key]?'+':''}`:'—';
 return <Box sx={{maxWidth:1500,mx:'auto'}}>
 <Stack direction="row" justifyContent="space-between" alignItems="center" gap={2} mb={3}><Box><Typography variant="overline" sx={{letterSpacing:3,color:'primary.main'}}>FUTURE JOBS / COMMAND CENTER</Typography><Typography variant="h3" sx={{fontWeight:850,fontSize:{xs:30,md:44},letterSpacing:-1.5}}>Your business. In focus.</Typography><Typography color="text.secondary" mt={1}>{data?.company.name||'Operations overview'}{data&&` · ${data.localDate} · ${data.company.timezone}`}</Typography></Box><Button startIcon={<Refresh/>} onClick={()=>void load()} disabled={loading}>Refresh</Button></Stack>
 {loading&&<LinearProgress sx={{mb:2}}/>}{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
 <Panel sx={{mb:3,position:'relative',overflow:'hidden',background:'linear-gradient(120deg,#092733,#10203a 65%,#1d2142)',color:'#effcff',borderColor:'#24526b'}}>
 <Stack direction={{xs:'column',md:'row'}} alignItems={{md:'center'}} justifyContent="space-between" gap={3}>
 <Box><Chip size="small" icon={<AutoAwesome/>} label="LUCY • OPERATIONS ASSISTANT" sx={{color:'#99eff5',bgcolor:'#143c49',mb:2}}/><Typography variant="h4" fontWeight={800}>Less chasing. More getting done.</Typography><Typography sx={{color:'#b5ccd8',maxWidth:650,mt:1}}>Review your team's work, surface exceptions, and prepare your next step with Lucy.</Typography></Box>
 <Button variant="contained" endIcon={<ArrowForward/>} onClick={()=>ask(data?.manager?'Brief me on what needs attention today':'Show my tasks and schedule')} sx={{whiteSpace:'nowrap',bgcolor:'#89f3d1',color:'#09242c',px:3,py:1.5}}>Give me my briefing</Button></Stack>
 <Stack direction="row" useFlexGap flexWrap="wrap" gap={1} mt={3}>{['Show this pay period','Show my tasks','Show the crew GPS status'].map(p=><Button key={p} onClick={()=>ask(p)} size="small" sx={{color:'#d3eef6',border:'1px solid #375468',borderRadius:8,px:2}}>{p}</Button>)}</Stack>
 </Panel>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',lg:'repeat(4,1fr)'},gap:2,mb:3}}>{[
 {key:'workforce',label:'People in view',icon:<Groups/>,path:'/team'},
 {key:'approvals',label:'Timesheets to review',icon:<TaskAlt/>,path:'/timesheet'},
 {key:'tasks',label:'Open tasks',icon:<CalendarMonth/>,path:'/tasks'},
 {key:'expenses',label:'Pending expenses',icon:<ReceiptLong/>,path:'/expenses'}].map(x=><Panel key={x.key}><Stack direction="row" justifyContent="space-between" color="text.secondary">{x.icon}<Button size="small" onClick={()=>nav(x.path)} aria-label={`Open ${x.label}`}><ArrowForward/></Button></Stack><Typography variant="h3" fontWeight={800} mt={1}>{count(x.key)}</Typography><Typography color="text.secondary">{x.label}</Typography>{data?.sections[x.key]?.status==='unavailable'&&<Typography color="warning.main" variant="caption">Temporarily unavailable</Typography>}</Panel>)}</Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.35fr 1fr'},gap:3}}>
 <Panel><Stack direction="row" justifyContent="space-between" mb={2}><Typography variant="h6" fontWeight={800}>Your attention queue</Typography><Chip size="small" label="Recorded work"/></Stack>
 {data?.sections.approvals?.status==='unavailable'&&<Alert severity="warning">Timesheet review data is unavailable.</Alert>}
 {rows('approvals').slice(0,6).map(r=><Stack key={r.id} direction="row" alignItems="center" justifyContent="space-between" sx={{py:1.8,borderBottom:'1px solid',borderColor:'divider'}}><Box><Typography fontWeight={700}>{r.employee}</Typography><Typography variant="body2" color="text.secondary">{new Date(r.clock_in).toLocaleString()} · {r.clock_out?'Awaiting review':'Open clock entry'}</Typography></Box><Button onClick={()=>nav('/timesheet')}>Review</Button></Stack>)}
 {data?.sections.approvals?.status==='ready'&&!rows('approvals').length&&<Typography color="text.secondary" py={3}>No timesheets currently need review.</Typography>}
 <Stack direction="row" gap={1} flexWrap="wrap" mt={2}><Button onClick={()=>nav('/pto')}>Leave requests: {count('leave')}</Button><Button onClick={()=>nav('/expenses')}>Expense review</Button><Button startIcon={<MapOutlined/>} onClick={()=>nav('/crew-tracking')}>Crew map</Button></Stack>
 </Panel>
 <Panel><Stack direction="row" alignItems="center" justifyContent="space-between"><Typography variant="h6" fontWeight={800}>{data?.manager?'Company pay period':'My next actions'}</Typography>{data?.manager&&<Button onClick={()=>setCalendar(true)}>Calendar</Button>}</Stack>
 {data?.periodError&&<Alert severity="warning" sx={{mt:2}}>{data.periodError}</Alert>}
 {data?.payPeriod&&<><Typography color="text.secondary" mt={2}>{data.payPeriod.start} → {data.payPeriod.end}</Typography><Typography variant="h3" fontWeight={800} mt={2}>{Number(data.payPeriod.totals.totalHours).toFixed(1)}<Typography component="span" color="text.secondary"> hours</Typography></Typography><Typography mt={1}>{data.payPeriod.totals.approved} approved · {data.payPeriod.totals.needsReview} to review</Typography><Stack gap={1} mt={3}><Button variant="outlined" onClick={()=>ask('Show this pay period and export it to Excel')}>Review & export timesheets</Button><Button variant="contained" onClick={()=>ask('Prepare payroll for this pay period')}>Prepare payroll with Lucy</Button><Typography variant="caption" color="text.secondary">Creates a draft for review. Draft calculations require payroll verification.</Typography></Stack></>}
 {!data?.manager&&<Stack gap={1} mt={2}><Button variant="outlined" onClick={()=>nav('/timesheet')}>Check my time</Button><Button variant="outlined" onClick={()=>nav('/schedule')}>Open my schedule</Button><Button variant="outlined" onClick={()=>nav('/expenses')}>Submit a receipt</Button></Stack>}
 </Panel>
 <Panel><Typography variant="h6" fontWeight={800} mb={2}>Workforce snapshot</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:1}}>{rows('workforce').slice(0,12).map(r=><Box key={r.id} sx={{p:1.5,border:'1px solid',borderColor:'divider',borderRadius:2}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{r.name}</Typography><Chip size="small" color={r.clock_in?'success':'default'} label={r.clock_in?'Clocked in':'Off clock'}/></Stack><Typography variant="caption" color="text.secondary">{r.project||'No active project'}</Typography></Box>)}</Box></Panel>
 <Panel><Typography variant="h6" fontWeight={800} mb={2}>Lucy action history</Typography>{rows('activity').map(r=><Box key={r.id} sx={{py:1.5,borderBottom:'1px solid',borderColor:'divider'}}><Typography fontWeight={700}>{r.title}</Typography><Typography variant="caption" color="text.secondary">{new Date(r.created_at).toLocaleString()}</Typography></Box>)}{!rows('activity').length&&<Typography color="text.secondary">{data?.sections.activity?.status==='unavailable'?'Action history is unavailable.':'Lucy actions will appear here as you work.'}</Typography>}</Panel>
 </Box>
 {data&&<Typography variant="caption" color="text.secondary" display="block" mt={2}>Snapshot updated {new Date(data.generatedAt).toLocaleTimeString()}. Lists are capped; open each module for full records.</Typography>}
 <Dialog open={calendar} onClose={()=>setCalendar(false)} fullWidth maxWidth="sm"><DialogTitle>Company payroll calendar</DialogTitle><DialogContent><Stack gap={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField select label="Schedule" value={settings.schedule} onChange={e=>setSettings({...settings,schedule:e.target.value})}>{['weekly','biweekly','semimonthly','monthly'].map(x=><MenuItem value={x} key={x}>{x}</MenuItem>)}</TextField><TextField label="Timezone" helperText="Example: America/Edmonton" value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/><TextField type="date" label="A known period start (required for biweekly)" InputLabelProps={{shrink:true}} value={settings.anchor} onChange={e=>setSettings({...settings,anchor:e.target.value})}/><TextField select label="Week starts" value={settings.weekStart} onChange={e=>setSettings({...settings,weekStart:Number(e.target.value)})}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((x,i)=><MenuItem key={x} value={i}>{x}</MenuItem>)}</TextField></Stack></DialogContent><DialogActions><Button onClick={()=>setCalendar(false)}>Cancel</Button><Button onClick={()=>void save()}>Save calendar</Button></DialogActions></Dialog>
 </Box>;
}
