import React,{useEffect,useState} from 'react';
import {Alert,Box,Button,MenuItem,Paper,Stack,TextField,Typography} from '@mui/material';
import {api} from '../services/api';
export default function Expenses(){
 const[rows,setRows]=useState<any[]>([]),[manager,setManager]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<File|null>(null);
 const[form,setForm]=useState({vendor:'',amount:'',spentOn:new Date().toLocaleDateString('en-CA'),currency:'CAD',notes:''});
 const load=async()=>{try{const d=await api.get<any>('/api/expenses');setRows(d.expenses);setManager(d.manager);}catch(e:any){setError(e.message);}};
 useEffect(()=>{void load();},[]);
 const scan=async()=>{if(!receipt)return;setBusy(true);setError('');try{if(!['image/png','image/jpeg','image/webp'].includes(receipt.type)||receipt.size>1000000)throw Error('Choose a PNG, JPEG or WebP receipt under 1 MB for extraction.');const image=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(receipt);});const result=await api.post<any>('/api/operations/receipts/extract',{image});const d=result.draft;setForm({...form,vendor:d.vendor||form.vendor,amount:d.amount==null?form.amount:String(d.amount),currency:d.currency||form.currency,spentOn:d.spentOn||form.spentOn,notes:form.notes+(d.category?'\nSuggested category: '+d.category:'')});setError('Receipt fields extracted. Verify every value against your receipt before submitting.');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{let attachmentId:string|undefined;
 if(receipt){const user=JSON.parse(localStorage.getItem('user')||'{}');const d=await api.uploadFileWithData<any>('/api/attachments/upload',receipt,{subjectUserId:user.id,category:'receipt'},'file');attachmentId=d.attachment.id;}
 await api.post('/api/expenses',{...form,amount:Number(form.amount),attachmentId});setForm({...form,vendor:'',amount:'',notes:''});setReceipt(null);await load();
 }catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const review=async(id:string,status:string)=>{setBusy(true);setError('');try{await api.post(`/api/expenses/${id}/review`,{status});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <Box sx={{maxWidth:1100,mx:'auto'}}><Typography variant="overline" color="primary">FIELD TO OFFICE</Typography><Typography variant="h3" fontWeight={800} mb={1}>Expenses & receipts</Typography><Typography color="text.secondary" mb={3}>Keep the receipt, the reason, and the review together. Approval does not send a payment.</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Paper component="form" onSubmit={submit} sx={{p:3,mb:3,borderRadius:3}}><Stack gap={2}><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth required label="Vendor" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><TextField required label="Amount" type="number" inputProps={{min:0.01,step:0.01}} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><TextField select label="Currency" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['CAD','USD'].map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><TextField required type="date" label="Expense date" InputLabelProps={{shrink:true}} value={form.spentOn} onChange={e=>setForm({...form,spentOn:e.target.value})}/></Stack><TextField label="Notes / business purpose" multiline rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><Stack direction="row" gap={2}><Button component="label" variant="outlined">{receipt?receipt.name:'Attach receipt'}<input hidden type="file" accept="image/*,.pdf" onChange={e=>setReceipt(e.target.files?.[0]||null)}/></Button><Button disabled={busy||!receipt} onClick={()=>void scan()}>Extract receipt fields</Button><Button type="submit" disabled={busy} variant="contained">Submit for review</Button></Stack></Stack></Paper>{rows.map(r=><Paper key={r.id} variant="outlined" sx={{p:2,mb:1,borderRadius:2}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography fontWeight={800}>{r.vendor} · {r.currency} {Number(r.amount).toFixed(2)}</Typography><Typography color="text.secondary">{String(r.spent_on).slice(0,10)} · {r.status}{r.attachment_id?' · Receipt attached':''}</Typography><Typography variant="body2">{r.notes}</Typography>{r.receipt_url&&/^https:\/\//.test(r.receipt_url)&&<Button component="a" href={r.receipt_url} target="_blank" rel="noopener noreferrer">Open receipt</Button>}</Box>{manager&&r.status==='pending'&&<Stack direction="row" gap={1}><Button disabled={busy} onClick={()=>void review(r.id,'approved')}>Approve</Button><Button disabled={busy} color="error" onClick={()=>void review(r.id,'rejected')}>Reject</Button></Stack>}</Stack></Paper>)}{!rows.length&&!error&&<Typography color="text.secondary">No expense claims yet.</Typography>}</Box>;
}
