import React,{useEffect,useState} from 'react';
import {Alert,Button,Checkbox,Container,FormControlLabel,Grid,MenuItem,Stack,TextField,Typography} from '@mui/material';
import {WorldwideInputs,worldwideInput} from './WorldwidePayrollEditor';
import {API_BASE} from '../services/api';
const empty={payDate:new Date().toISOString().slice(0,10),gross:0,cppYtd:0,cpp2Ytd:0,eiYtd:0,pensionableYtd:0,additionalTax:0,standardCaseConfirmed:false};
export default function ManualPayroll(){
 const [rules,setRules]=useState<any>(null);
 const [payrolls,setPayrolls]=useState<any[]>([]),[id,setId]=useState(''),[detail,setDetail]=useState<any>(null),[itemId,setItemId]=useState(''),[input,setInput]=useState<any>(empty),[revision,setRevision]=useState(0),[reference,setReference]=useState(''),[paidOn,setPaidOn]=useState(empty.payDate),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const call=async(path:string,body?:any)=>{const r=await fetch(API_BASE+'/api'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+localStorage.getItem('token'),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.message);return d;};
 const load=async()=>{setPayrolls((await call('/payroll')).payrolls);const config=(await call('/payroll-rules')).current;setRevision(config?.revision||0);setRules(config?.rules||null);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const refresh=async()=>{if(id)setDetail(await call('/manual-payroll/'+id));await load();};
 const run=async(fn:()=>Promise<any>)=>{setError('');setMessage('');setBusy(true);try{const d=await fn();if(d?.message)setMessage(d.message);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const item=detail?.items.find((v:any)=>v.id===itemId),approved=detail?.payroll.status==='approved'||detail?.payroll.status==='paid';
 return <Container sx={{py:3}}><Typography variant="h4">Payroll & Manual Payments</Typography><Alert severity="info" sx={{my:2}}>This app does not send money. Calculate and independently review payroll, pay employees through your bank, then record your confirmation. Recorded payment is not bank-verified settlement.</Alert>
 <Stack direction="row" spacing={2}><Button href="/payroll">Prepare payroll draft</Button><Button href="/payroll-rules">Company payroll rules</Button><Button onClick={()=>run(refresh)}>Refresh</Button></Stack>
 {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 <TextField fullWidth select label="Payroll" value={id} sx={{my:2}} onChange={e=>{const next=e.target.value;setId(next);setItemId('');setConfirmed(false);setReference('');run(async()=>setDetail(await call('/manual-payroll/'+next)));}}>{payrolls.map(p=><MenuItem key={p.id} value={p.id}>{String(p.period_start).slice(0,10)} — {String(p.period_end).slice(0,10)} · {p.status}</MenuItem>)}</TextField>
 {detail&&<><Typography>Saved rule revision: {revision||'Not configured'}. Payroll status: {detail.payroll.status}.</Typography><TextField fullWidth select label="Employee" value={itemId} sx={{my:2}} onChange={e=>{const next=detail.items.find((v:any)=>v.id===e.target.value);setItemId(e.target.value);setConfirmed(false);setReference('');const gross=Number(next.calculation_snapshot?.gross??(Number(next.hours)*Number(next.hourly_rate)+Number(next.adjustments||0)+Number(next.cpp_deduction||0)+Number(next.ei_deduction||0)+Number(next.tax_deduction||0)));setInput(rules?.engine==='company_rules_v1'?worldwideInput(rules,gross):{...empty,gross});setPaidOn(next.calculation_snapshot?.payDate||empty.payDate);}}>{detail.items.map((v:any)=><MenuItem key={v.id} value={v.id}>{v.first_name} {v.last_name} · {v.payment_reference?'Payment recorded':v.calculation_snapshot?'Calculated — review required':'Uncalculated'}</MenuItem>)}</TextField>
 {item&&!approved&&rules?.engine!=='company_rules_v1'&&<><Alert severity="warning">Standard Alberta 2026 regular wages only. Confirm gross wages and current employer YTD records. No bonuses, special benefits, pension/RRSP deductions, Quebec transfers, partial-year CPP eligibility or special credits. Default zero YTD is only correct when no prior pay exists.</Alert><Grid container spacing={2} sx={{mt:1}}>{Object.keys(input).filter(k=>k!=='standardCaseConfirmed').map(k=><Grid item xs={12} sm={4} key={k}><TextField fullWidth label={k} type={k==='payDate'?'date':'number'} InputLabelProps={{shrink:true}} value={input[k]} onChange={e=>setInput({...input,[k]:k==='payDate'?e.target.value:e.target.value===''?'':Number(e.target.value)})}/></Grid>)}</Grid><FormControlLabel control={<Checkbox checked={input.standardCaseConfirmed} onChange={e=>setInput({...input,standardCaseConfirmed:e.target.checked})}/>} label="I confirm this employee and payment meet the stated calculation scope."/><Button disabled={busy||!revision||!input.standardCaseConfirmed} onClick={()=>run(async()=>{const d=await call('/manual-payroll/'+id+'/calculate',{itemId,rulesRevision:revision,input});await refresh();return d;})}>Calculate and save for review</Button></>}
 {item&&!approved&&rules?.engine==='company_rules_v1'&&<><WorldwideInputs rules={rules} input={input} setInput={setInput}/><Button disabled={busy||!input.companyRulesConfirmed} onClick={()=>run(async()=>{const d=await call('/manual-payroll/'+id+'/calculate',{itemId,rulesRevision:revision,input});await refresh();return d;})}>Calculate and save for review</Button></>}
 {item?.calculation_snapshot?.lines&&<><Typography>Company-configured deductions and employer costs</Typography>{item.calculation_snapshot.lines.map((l:any)=><Typography key={l.id}>{l.label} ({l.category}): {l.amount} {item.calculation_snapshot.currency}</Typography>)}</>}
 {item?.calculation_snapshot&&<Alert severity="info" sx={{my:2}}>Gross {item.calculation_snapshot.gross}{!item.calculation_snapshot.lines&&<> · CPP {item.calculation_snapshot.cpp} · CPP2 {item.calculation_snapshot.cpp2} · EI {item.calculation_snapshot.ei}</>} · Income tax {item.calculation_snapshot.incomeTax} · Net {item.calculation_snapshot.net} {item.calculation_snapshot.currency}. {item.calculation_snapshot.classification}</Alert>}
 {!approved&&<><TextField fullWidth sx={{my:2}} label="Independent local payroll review reference" value={reference} onChange={e=>setReference(e.target.value)}/><FormControlLabel control={<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>} label="I checked every employee's gross, YTD and deductions independently. This records company review, not government approval."/><Button disabled={busy||!confirmed||reference.trim().length<8} onClick={()=>run(async()=>{const d=await call('/manual-payroll/'+id+'/review',{reference,confirmed});setConfirmed(false);setReference('');await refresh();return d;})}>Approve reviewed payroll</Button></>}
 {approved&&item&&!item.payment_reference&&<><Typography>Make the payment through your bank first. Exact net amount: {item.calculation_snapshot?.net} {item.calculation_snapshot?.currency}.</Typography><TextField sx={{my:2}} type="date" label="Actual payment date" InputLabelProps={{shrink:true}} value={paidOn} onChange={e=>setPaidOn(e.target.value)}/><TextField fullWidth label="Bank payment reference — no account numbers" value={reference} onChange={e=>setReference(e.target.value)}/><FormControlLabel control={<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>} label="I confirm I completed this exact payment through our bank."/><Button disabled={busy||!confirmed||reference.trim().length<4} onClick={()=>run(async()=>{const d=await call('/manual-payroll/'+id+'/record-payment',{itemId,paidOn,reference,amount:item.calculation_snapshot.net,confirmed});setConfirmed(false);setReference('');await refresh();return d;})}>Record external payment</Button></>}
 {item?.payment_reference&&<Alert severity="success">External payment recorded: {item.payment_reference}, {String(item.paid_on).slice(0,10)}.</Alert>}
 </>}
 </Container>;
}
