import React,{useEffect,useState} from 'react';
import {Alert,Box,Button,Container,Grid,MenuItem,Stack,TextField,Typography,Checkbox,FormControlLabel} from '@mui/material';
import WorldwidePayrollEditor from './WorldwidePayrollEditor';
import {API_BASE} from '../services/api';
export default function PayrollRules(){
 const [metadata,setMetadata]=useState<any>(null);
 const [rules,setRules]=useState<any>(null),[revision,setRevision]=useState(0),[history,setHistory]=useState<any[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);
 const [input,setInput]=useState<any>({payDate:new Date().toISOString().slice(0,10),gross:2000,cppYtd:0,cpp2Ytd:0,eiYtd:0,pensionableYtd:0,additionalTax:0,standardCaseConfirmed:false});
 const call=async(path:string,body?:any)=>{const r=await fetch(API_BASE+'/api/payroll-rules'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+localStorage.getItem('token'),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.message);return d;};
 const load=async()=>{try{const d=await call('');setMetadata(d);setRules(d.current?.rules||d.template);setRevision(d.current?.revision||0);setHistory(d.history);}catch(e:any){setError(e.message);}};
 useEffect(()=>{void load();},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 if(!rules)return <Container><Alert severity="info">{error||'Loading company payroll rules...'}</Alert></Container>;
 if(rules.engine==='company_rules_v1')return <Container sx={{py:3}}><Typography variant="h4">Worldwide company payroll rules</Typography><Typography>Saved revision {revision}. Changes affect new calculations only.</Typography>{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}<Button href="/direct-deposit">Payroll & Manual Payments</Button><Button onClick={()=>setRules(metadata.template)}>Use Alberta reference template</Button><WorldwidePayrollEditor rules={rules} setRules={setRules} countries={metadata.countries} currencies={metadata.currencies} busy={busy} preview={i=>void run(async()=>setResult((await call('/preview',{rules,input:i})).result))}/><TextField fullWidth label="Reason for this revision" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy||reason.trim().length<8} onClick={()=>run(async()=>{await call('',{rules,expectedRevision:revision,reason});await load();setMessage('New company rule revision saved.');})}>Save revision</Button><TextField fullWidth select label="Load a historical revision" value="" onChange={e=>setRules(history.find(h=>h.revision===Number(e.target.value)).rules)}>{history.map(h=><MenuItem key={h.revision} value={h.revision}>Revision {h.revision}: {h.reason}</MenuItem>)}</TextField>{result&&<Box component="pre" sx={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result,null,2)}</Box>}</Container>;
 return <Container sx={{py:3}}><Typography variant="h4">Company payroll rules</Typography><Typography sx={{my:2}}>Revision {revision}. Changes apply to new calculations only. Existing payroll snapshots and payment records stay unchanged.</Typography>
 <Alert severity="warning">All calculations require review. Statutory overrides are custom rules, not verified tax compliance. Currently supported: Alberta/CAD, 2026 regular cash wages, full-year CPP eligibility and standard EI. No bonuses, Quebec transfers, noncash benefits, commission, special deductions or credits.</Alert>
 {error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}
 <Button onClick={()=>setRules(metadata.worldwideTemplate)}>Configure worldwide company rules</Button><Button href="/direct-deposit" sx={{my:2}}>Payroll & Manual Payments</Button>
 <Grid container spacing={2}>{['country','subdivision','currency','effectiveFrom','effectiveTo'].map(k=><Grid item xs={12} sm={4} key={k}><TextField fullWidth label={k} type={k.startsWith('effective')?'date':'text'} InputLabelProps={{shrink:true}} value={rules[k]} onChange={e=>setRules({...rules,[k]:e.target.value})}/></Grid>)}
 {Object.keys(rules.policy).map(k=><Grid item xs={12} sm={4} key={k}><TextField fullWidth type="number" label={k} helperText={k==='vacationAccrualRate'?'Preview accrual only; employee vacation settings govern draft pay':undefined} value={rules.policy[k]} onChange={e=>setRules({...rules,policy:{...rules.policy,[k]:e.target.value===''?'':Number(e.target.value)}})}/></Grid>)}</Grid>
 <Typography variant="h6" sx={{mt:3}}>Statutory rules — advanced edits require independent review</Typography><Typography variant="body2">Rates are decimals. Bracket constants use the CRA formula rate × annual income − constant. Do not substitute another country's brackets into the Alberta engine.</Typography>
 <Grid container spacing={2} sx={{mt:1}}>{Object.keys(rules.statutory).filter(k=>!k.endsWith('Brackets')).map(k=><Grid item xs={12} sm={4} key={k}><TextField fullWidth type="number" label={k} value={rules.statutory[k]} onChange={e=>setRules({...rules,statutory:{...rules.statutory,[k]:e.target.value===''?'':Number(e.target.value)}})}/></Grid>)}</Grid>
 {['federalBrackets','provincialBrackets'].map(k=><Box key={k} sx={{mt:2}}><Typography>{k}</Typography>{rules.statutory[k].map((br:any,index:number)=><Stack key={index} direction="row" spacing={1} sx={{my:1}}>{['floor','rate','constant'].map(field=><TextField key={field} type="number" label={field} value={br[field]} onChange={e=>{const arr=rules.statutory[k].map((v:any,j:number)=>j===index?{...v,[field]:e.target.value===''?'':Number(e.target.value)}:v);setRules({...rules,statutory:{...rules.statutory,[k]:arr}});}}/>)}</Stack>)}</Box>)}
 <TextField fullWidth sx={{mt:2}} label="Reason for change and review reference" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy||reason.trim().length<8} variant="contained" sx={{my:2}} onClick={()=>run(async()=>{await call('',{rules,expectedRevision:revision,reason});await load();setMessage('New revision saved. No existing payroll was recalculated.');})}>Save new revision</Button>
 <TextField select fullWidth label="Load a historical revision into the editor" value="" onChange={e=>{const h=history.find(v=>v.revision===Number(e.target.value));if(h){setRules(h.rules);setReason('Restore rules from revision '+h.revision);}}}>{history.map(h=><MenuItem key={h.revision} value={h.revision}>Revision {h.revision}: {h.reason}</MenuItem>)}</TextField>
 <Typography variant="h6" sx={{my:2}}>Preview only — does not change payroll or make payments</Typography><Grid container spacing={2}>{Object.keys(input).filter(k=>k!=='standardCaseConfirmed').map(k=><Grid item xs={12} sm={4} key={k}><TextField fullWidth label={k} type={k==='payDate'?'date':'number'} InputLabelProps={{shrink:true}} value={input[k]} onChange={e=>setInput({...input,[k]:k==='payDate'?e.target.value:e.target.value===''?'':Number(e.target.value)})}/></Grid>)}</Grid>
 <FormControlLabel control={<Checkbox checked={input.standardCaseConfirmed} onChange={e=>setInput({...input,standardCaseConfirmed:e.target.checked})}/>} label="This example meets the standard-case limits above; YTD amounts exclude this payment."/>
 <Button disabled={busy||!input.standardCaseConfirmed} onClick={()=>run(async()=>setResult((await call('/preview',{rules,input})).result))}>Preview calculation</Button>{result&&<Box component="pre" sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',p:2}}>{JSON.stringify(result,null,2)}</Box>}
 <Typography sx={{mt:2}}>Rule sources: <a href="https://www.canada.ca/en/revenue-agency/services/forms-publications/payroll/t4127-payroll-deductions-formulas.html" target="_blank" rel="noreferrer">CRA T4127</a>. Reference rules are not government certification of this software.</Typography>
 </Container>;
}
