import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Alert,Box,Button,Chip,CircularProgress,Container,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,Grid,IconButton,InputLabel,MenuItem,Paper,Select,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography}from'@mui/material';
import{CheckCircle,ChevronLeft,ChevronRight,Download,Edit,Timer}from'@mui/icons-material';
import{API_BASE}from'../services/api';
type Entry={id:string;project_name:string;project_address:string;clock_in:string;clock_out:string|null;break_minutes:number;hours:string;regularHours:string;overtimeHours:string;approval_status:string;correction_reason:string;payroll_locked:boolean;alerts:string[]};
type Employee={id:string;first_name:string;last_name:string;email:string};
const iso=(d:Date)=>d.toISOString().slice(0,10),localInput=(v:string|null)=>v?new Date(v).toISOString().slice(0,16):'';
export default function Timesheet(){
 const token=localStorage.getItem('token')||'',user=JSON.parse(localStorage.getItem('user')||'{}'),manager=['boss','manager','admin'].includes(String(user.role||'').toLowerCase());
 const[entries,setEntries]=useState<Entry[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[selectedUser,setSelectedUser]=useState(user.id||''),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[editing,setEditing]=useState<Entry|null>(null),[form,setForm]=useState<any>({});
 const base=new Date();base.setDate(base.getDate()+offset*7);const day=base.getDay(),start=new Date(base);start.setDate(base.getDate()-day+(day===0?-6:1));start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);const weekStart=iso(start),weekEnd=iso(end);
 const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
 const load=useCallback(async()=>{if(!selectedUser)return;setLoading(true);setError('');try{const r=await fetch(`${API_BASE}/api/time-entries?userId=${selectedUser}&start=${weekStart}&end=${weekEnd}`,{headers,cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load timesheet');setEntries(d.entries||[]);}catch(e:any){setError(e.message)}finally{setLoading(false)}},[selectedUser,weekStart,weekEnd,token]);
 useEffect(()=>{if(manager)fetch(`${API_BASE}/api/users/company`,{headers}).then(r=>r.json()).then(d=>setEmployees(d.users||[])).catch(()=>{});},[manager,token]);useEffect(()=>{load()},[load]);
 const totals=useMemo(()=>entries.reduce((a,e)=>({hours:a.hours+Number(e.hours||0),regular:a.regular+Number(e.regularHours||0),ot:a.ot+Number(e.overtimeHours||0)}),{hours:0,regular:0,ot:0}),[entries]);
 const edit=(e:Entry)=>{setEditing(e);setForm({clockIn:localInput(e.clock_in),clockOut:localInput(e.clock_out),breakMinutes:e.break_minutes||0,reason:''})};
 const save=async()=>{if(!editing)return;try{const r=await fetch(`${API_BASE}/api/workforce-operations/time-entries/${editing.id}`,{method:'PATCH',headers,body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Correction failed');setEditing(null);setSuccess('Timesheet corrected and returned for approval.');load()}catch(e:any){setError(e.message)}};
 const approve=async(id:string)=>{try{const r=await fetch(`${API_BASE}/api/workforce-operations/time-entries/${id}/approve`,{method:'POST',headers}),d=await r.json();if(!r.ok)throw new Error(d.message||'Approval failed');setSuccess('Time entry approved for payroll.');load()}catch(e:any){setError(e.message)}};
 const exportCsv=async()=>{const r=await fetch(`${API_BASE}/api/time-entries/export?userId=${selectedUser}&start=${weekStart}&end=${weekEnd}`,{headers});if(!r.ok)return setError('Export failed');const b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`timesheet_${weekStart}_${weekEnd}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <Container maxWidth="xl" sx={{py:4,color:'#fff'}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2,flexWrap:'wrap',mb:3}}><Box><Typography variant="h4" fontWeight={900}><Timer sx={{mr:1,verticalAlign:'middle'}}/>Timesheet control center</Typography><Typography color="text.secondary">Review field time, correct exceptions, approve hours and protect payroll records.</Typography></Box><Button variant="outlined" startIcon={<Download/>} onClick={exportCsv}>Export CSV</Button></Box>{error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}} onClose={()=>setSuccess('')}>{success}</Alert>}
 <Paper sx={{p:2,bgcolor:'#12171e',border:'1px solid #303846',mb:2}}><Box sx={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:2,flexWrap:'wrap'}}><Box sx={{display:'flex',alignItems:'center'}}><IconButton onClick={()=>setOffset(v=>v-1)}><ChevronLeft/></IconButton><Typography fontWeight={800}>{weekStart} — {weekEnd}</Typography><IconButton onClick={()=>setOffset(v=>v+1)}><ChevronRight/></IconButton></Box>{manager&&<FormControl size="small" sx={{minWidth:240}}><InputLabel>Employee</InputLabel><Select value={selectedUser} label="Employee" onChange={e=>setSelectedUser(String(e.target.value))}>{employees.map(e=><MenuItem key={e.id} value={e.id}>{e.first_name} {e.last_name}</MenuItem>)}</Select></FormControl>}</Box></Paper>
 <Grid container spacing={2} sx={{mb:2}}>{[['Total hours',totals.hours,'#00d4ff'],['Regular',totals.regular,'#55d66b'],['Overtime',totals.ot,'#ffb020'],['Entries',entries.length,'#b084ff']].map(([l,v,c])=><Grid item xs={6} md={3} key={String(l)}><Paper sx={{p:2,bgcolor:'#171d25',border:'1px solid #303846'}}><Typography color="text.secondary">{l}</Typography><Typography variant="h5" fontWeight={900} sx={{color:c}}>{Number(v).toFixed(l==='Entries'?0:2)}{l!=='Entries'&&'h'}</Typography></Paper></Grid>)}</Grid>
 <TableContainer component={Paper} sx={{bgcolor:'#11161d',border:'1px solid #303846'}}><Table><TableHead><TableRow><TableCell>Date & time</TableCell><TableCell>Job</TableCell><TableCell>Break</TableCell><TableCell>Regular</TableCell><TableCell>OT</TableCell><TableCell>Status</TableCell>{manager&&<TableCell align="right">Actions</TableCell>}</TableRow></TableHead><TableBody>{loading?<TableRow><TableCell colSpan={7} align="center"><CircularProgress/></TableCell></TableRow>:entries.map(e=><TableRow key={e.id}><TableCell><Typography variant="body2">{new Date(e.clock_in).toLocaleString()}</Typography><Typography variant="caption" color="text.secondary">{e.clock_out?new Date(e.clock_out).toLocaleString():'In progress'}</Typography></TableCell><TableCell>{e.project_name}<Typography variant="caption" display="block" color="text.secondary">{e.project_address}</Typography></TableCell><TableCell>{e.break_minutes}m</TableCell><TableCell>{e.regularHours}h</TableCell><TableCell>{e.overtimeHours}h</TableCell><TableCell><Chip size="small" color={e.payroll_locked?'default':e.approval_status==='approved'?'success':e.approval_status==='needs_review'?'warning':'info'} label={e.payroll_locked?'Payroll locked':e.approval_status.replace('_',' ')}/></TableCell>{manager&&<TableCell align="right"><IconButton disabled={e.payroll_locked} onClick={()=>edit(e)}><Edit/></IconButton><IconButton color="success" disabled={e.payroll_locked||!e.clock_out||e.approval_status==='approved'} onClick={()=>approve(e.id)}><CheckCircle/></IconButton></TableCell>}</TableRow>)}</TableBody></Table></TableContainer>
 <Dialog open={Boolean(editing)} onClose={()=>setEditing(null)} fullWidth maxWidth="sm"><DialogTitle>Correct time entry</DialogTitle><DialogContent sx={{display:'grid',gap:2,pt:'16px!important'}}><Alert severity="warning">The original values are preserved in the audit log. Payroll-locked entries cannot be changed.</Alert><TextField type="datetime-local" label="Clock in" InputLabelProps={{shrink:true}} value={form.clockIn||''} onChange={e=>setForm({...form,clockIn:e.target.value})}/><TextField type="datetime-local" label="Clock out" InputLabelProps={{shrink:true}} value={form.clockOut||''} onChange={e=>setForm({...form,clockOut:e.target.value})}/><TextField type="number" label="Unpaid break minutes" value={form.breakMinutes||0} onChange={e=>setForm({...form,breakMinutes:Number(e.target.value)})}/><TextField multiline minRows={2} label="Required correction reason" value={form.reason||''} onChange={e=>setForm({...form,reason:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setEditing(null)}>Cancel</Button><Button variant="contained" onClick={save}>Save correction</Button></DialogActions></Dialog></Container>;
}
