import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Box,Button,Card,Chip,Divider,FormControl,IconButton,InputLabel,MenuItem,Select,Tab,Tabs,TextField,Typography} from '@mui/material';
import {Calculate,ContentCopy,Download,Engineering,Favorite,FavoriteBorder,FolderOpen,History,SafetyCheck,Search} from '@mui/icons-material';
import {calculators,convert,UnitFamily,units} from '../services/workerTools';
import {useNavigate,useParams} from 'react-router-dom';
import ConstructionCalculator from '../components/ConstructionCalculator';

const safeNumber=(s:string)=>{const v=Number(s);return Number.isFinite(v)?v:0};
export default function WorkerTools(){
 const navigate=useNavigate();
 const {calculatorId}=useParams<{calculatorId?:string}>();
 const calculatorPanel=useRef<HTMLDivElement|null>(null);
 const [tab,setTab]=useState(0),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[showAll,setShowAll]=useState(false),[selected,setSelected]=useState(()=>calculatorId&&calculators.some(c=>c.id===calculatorId)?calculatorId:'concrete');
 const [values,setValues]=useState<Record<string,string>>({}),[favorites,setFavorites]=useState<string[]>(()=>JSON.parse(localStorage.getItem('workerTools:favorites')||'[]'));
 const [family,setFamily]=useState<UnitFamily>('length'),[from,setFrom]=useState('ft'),[to,setTo]=useState('m'),[convertValue,setConvertValue]=useState('1'),[tape,setTape]=useState<string[]>(()=>JSON.parse(localStorage.getItem('workerTools:tape')||'[]'));
 const calc=calculators.find(x=>x.id===selected)||calculators[0];
 useEffect(()=>{
  if(calculatorId&&calculators.some(c=>c.id===calculatorId))setSelected(calculatorId);
 },[calculatorId]);
 useEffect(()=>localStorage.setItem('workerTools:favorites',JSON.stringify(favorites)),[favorites]); useEffect(()=>localStorage.setItem('workerTools:tape',JSON.stringify(tape.slice(0,100))),[tape]);
 const categories=useMemo(()=>['All',...Array.from(new Set(calculators.map(c=>c.category)))],[ ]);
 const filtered=useMemo(()=>calculators.filter(c=>(category==='All'||c.category===category)&&(c.name+c.category+c.description).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(favorites.includes(b.id))-Number(favorites.includes(a.id))||a.name.localeCompare(b.name)),[query,category,favorites]);
 const visibleTools=query||showAll||category!=='All'?filtered:filtered.slice(0,8);
 const results=useMemo(()=>{try{return calc.solve(Object.fromEntries(calc.fields.map(x=>[x.key,safeNumber(values[x.key]??String(x.default??''))])))}catch{return {Result:'Check inputs'}}},[calc,values]);
 const addTape=(line:string)=>setTape(t=>[`${new Date().toLocaleString()} â€” ${line}`,...t].slice(0,100));
 const exportTape=()=>{const blob=new Blob([tape.join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='future-jobs-measure-tape.txt';a.click();URL.revokeObjectURL(a.href)};
 const unitNames=Object.keys(units[family]);
 const selectCalculator=(id:string)=>{
  setSelected(id);
  navigate('/worker-tools/'+encodeURIComponent(id));
  setValues({});
  window.setTimeout(()=>calculatorPanel.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);
 };
 return <Box sx={{p:{xs:2,md:3},maxWidth:1500,mx:'auto'}}>
  <Box sx={{display:'flex',gap:2,alignItems:'center',mb:2}}><Box sx={{p:1.4,borderRadius:3,bgcolor:'rgba(103,232,249,.12)',color:'#67E8F9'}}><Engineering/></Box><Box><Typography variant="h4" fontWeight={950}>Worker Tools</Typography><Typography color="text.secondary">Offline-ready calculators, field references, safety aids and project shortcuts.</Typography></Box></Box>
  <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab icon={<Calculate/>} iconPosition="start" label="Calculators"/><Tab icon={<FolderOpen/>} iconPosition="start" label="Field Desk"/><Tab icon={<SafetyCheck/>} iconPosition="start" label="Safety"/><Tab icon={<History/>} iconPosition="start" label="Tape"/></Tabs><Divider sx={{mb:3}}/>
  {tab===0&&<Box ref={calculatorPanel} sx={{display:'flex',flexDirection:'column',gap:3,scrollMarginTop:24}}>
   {calculatorId&&<Box><Button onClick={()=>navigate('/worker-tools')}>← All Worker Tools</Button></Box>}
   {calculatorId&&<Card variant="outlined" sx={{p:{xs:2,md:3}}}><Typography variant="h5" fontWeight={900}>{calc.name}</Typography><Typography color="text.secondary" mb={2}>{calc.description}</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)'},gap:2}}>{calc.fields.map(field=><TextField key={field.key} type="number" label={`${field.label}${field.unit?' ('+field.unit+')':''}`} value={values[field.key]??field.default??''} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))}/>)}</Box><Box sx={{mt:3,p:2,borderRadius:2,bgcolor:'rgba(103,232,249,.07)',display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(3,1fr)'},gap:2}}>{Object.entries(results).map(([k,v])=><Box key={k}><Typography variant="caption" color="text.secondary">{k}</Typography><Typography variant="h6" fontWeight={900}>{v}</Typography></Box>)}</Box><Button sx={{mt:2}} onClick={()=>addTape(`${calc.name}: ${Object.entries(results).map(([k,v])=>`${k} ${v}`).join(', ')}`)}>Add result to tape</Button></Card>}
   <Card variant="outlined" sx={{p:{xs:1,md:2},overflow:'hidden'}}><Typography variant="h5" fontWeight={900} sx={{px:1,pt:1}}>Construction console</Typography><Typography color="text.secondary" sx={{px:1,mb:2}}>A jobsite keypad for dimensional arithmetic, unit conversion, memory, circles, board feet and a paperless tape.</Typography><ConstructionCalculator onTape={addTape}/>
    <Typography fontWeight={850} mt={3} mb={1}>Universal converter</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'},gap:1}}><FormControl><InputLabel>Family</InputLabel><Select label="Family" value={family} onChange={e=>{const f=e.target.value as UnitFamily;setFamily(f);const k=Object.keys(units[f]);setFrom(k[0]);setTo(k[1])}}>{Object.keys(units).map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField type="number" label="Value" value={convertValue} onChange={e=>setConvertValue(e.target.value)}/><FormControl><InputLabel>From</InputLabel><Select label="From" value={from} onChange={e=>setFrom(e.target.value)}>{unitNames.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>To</InputLabel><Select label="To" value={to} onChange={e=>setTo(e.target.value)}>{unitNames.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl></Box><Typography variant="h5" mt={2}>{Number.isFinite(convert(safeNumber(convertValue),family,from,to))?`${convert(safeNumber(convertValue),family,from,to).toLocaleString(undefined,{maximumFractionDigits:8})} ${to}`:'—'}</Typography>
   </Card>
   {!calculatorId&&<Box><Typography variant="h5" fontWeight={900} mb={.5}>Trade calculators</Typography><Typography color="text.secondary" mb={2}>Choose a tool to open its complete dedicated calculator.</Typography><TextField fullWidth size="small" placeholder="Search 31 trade calculators" value={query} onChange={e=>setQuery(e.target.value)} InputProps={{startAdornment:<Search sx={{mr:1}}/>}}/><Box sx={{display:'flex',gap:1,overflowX:'auto',py:2}}>{categories.map(x=><Chip key={x} label={x} clickable color={category===x?'info':'default'} variant={category===x?'filled':'outlined'} onClick={()=>{setCategory(x);setShowAll(false)}}/>)}</Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'repeat(2,minmax(0,1fr))',md:'repeat(3,minmax(0,1fr))',xl:'repeat(4,minmax(0,1fr))'},gap:1.5}}>{visibleTools.map(c=><Card key={c.id} variant="outlined" onClick={()=>selectCalculator(c.id)} sx={{p:{xs:1.25,sm:1.75},cursor:'pointer',minHeight:145,display:'flex',flexDirection:'column','&:hover':{borderColor:'#67E8F9',transform:'translateY(-2px)'},transition:'all .18s'}}><Box sx={{display:'flex',gap:.5}}><Typography fontWeight={850} sx={{flex:1,lineHeight:1.2}}>{c.name}</Typography><IconButton size="small" aria-label={`Favorite ${c.name}`} onClick={e=>{e.stopPropagation();setFavorites(f=>f.includes(c.id)?f.filter(x=>x!==c.id):[...f,c.id])}}>{favorites.includes(c.id)?<Favorite color="error" fontSize="small"/>:<FavoriteBorder fontSize="small"/>}</IconButton></Box><Typography variant="caption" color="text.secondary" sx={{flex:1,mt:.75}}>{c.description}</Typography><Chip size="small" label={c.category} sx={{alignSelf:'flex-start',mt:1}}/></Card>)}</Box>{filtered.length===0&&<Typography color="text.secondary" sx={{py:4,textAlign:'center'}}>No tools match that search.</Typography>}{!query&&category==='All'&&filtered.length>8&&<Button variant="outlined" onClick={()=>setShowAll(x=>!x)} sx={{mt:2}}>{showAll?'Show fewer tools':`Show all ${filtered.length} tools`}</Button>}</Box>}
  </Box>}
  {tab===1&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:2}}>{[['Project documents','Open drawings, photos and evidence already stored by project.','/media'],['Plan measurement','Use Measure Master for calibrated dimensions; attach marked-up site images in Evidence Center.','/evidence'],['Field capture','Capture photos, voice notes, GPS evidence and signatures from existing project workflows.','/projects']].map(([a,b,c])=><Card key={a} variant="outlined" sx={{p:3}}><Typography variant="h6" fontWeight={900}>{a}</Typography><Typography color="text.secondary" minHeight={70}>{b}</Typography><Button href={c}>Open</Button></Card>)}</Box>}
  {tab===2&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,1fr)'},gap:2}}>{[['Pre-job hazard check',['Scope understood','PPE inspected','Utilities identified','Access and egress clear','Emergency contact confirmed']],['Vehicle & equipment check',['Visible damage checked','Brakes and controls tested','Guards installed','Fuel/charge adequate','Defects reported']],['Toolbox talk',['Todayâ€™s work reviewed','Top hazards named','Controls assigned','Weather considered','Crew questions recorded']],['End-of-shift closeout',['Work area secured','Tools accounted for','Waste removed','Incidents reported','Photos attached']]].map(([title,items])=><Card key={title as string} variant="outlined" sx={{p:3}}><Typography variant="h6" fontWeight={900}>{title as string}</Typography>{(items as string[]).map(x=><Typography key={x} sx={{mt:1}}>â–¡ {x}</Typography>)}</Card>)}</Box>}
  {tab===3&&<Card variant="outlined" sx={{p:3}}><Box sx={{display:'flex',justifyContent:'space-between'}}><Typography variant="h5" fontWeight={900}>Paperless tape</Typography><Box><IconButton aria-label="Copy tape" onClick={()=>navigator.clipboard.writeText(tape.join('\n'))}><ContentCopy/></IconButton><IconButton aria-label="Download tape" onClick={exportTape}><Download/></IconButton></Box></Box>{tape.length===0?<Typography color="text.secondary" mt={2}>Saved calculations appear here.</Typography>:tape.map((x,i)=><Typography key={i} sx={{fontFamily:'monospace',py:1,borderBottom:'1px solid',borderColor:'divider'}}>{x}</Typography>)}<Button color="error" onClick={()=>setTape([])} sx={{mt:2}}>Clear tape</Button></Card>}
  <Typography variant="caption" color="text.secondary" display="block" mt={3}>Field estimates only. Verify structural, electrical, code, safety and regulated work with qualified professionals and local requirements.</Typography>
 </Box>
}

