import React,{useState} from 'react';
import {Alert,Box,Button,Checkbox,FormControlLabel,MenuItem,Stack,TextField,Typography} from '@mui/material';
export const worldwideInput=(rules:any,gross=0)=>({payDate:new Date().toISOString().slice(0,10),gross,taxable:gross,manualAmounts:Object.fromEntries(rules.lines.filter((l:any)=>l.method==='manual').map((l:any)=>[l.id,''])),ytd:Object.fromEntries(rules.lines.filter((l:any)=>l.annualCap!==null).map((l:any)=>[l.id,''])),reviewReference:'',companyRulesConfirmed:false});
const label=(s:string)=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase());
const num=(s:string)=>s===''?'':Number(s);
export function WorldwideInputs({rules,input,setInput}:{rules:any;input:any;setInput:(v:any)=>void}){return <Box><Alert severity="warning">Enter reviewed gross and taxable pay. Taxable pay is supplied independently, not derived from deductions. No country-specific compliance, filing or payment is implied.</Alert><Stack spacing={2} sx={{my:2}}>{['payDate','gross','taxable','reviewReference'].map(k=><TextField key={k} label={label(k)} type={k==='payDate'?'date':['gross','taxable'].includes(k)?'number':'text'} InputLabelProps={{shrink:true}} value={input[k]??''} onChange={e=>setInput({...input,[k]:['gross','taxable'].includes(k)?num(e.target.value):e.target.value})}/>)}{rules.lines.filter((l:any)=>l.method==='manual').map((l:any)=><TextField key={l.id} type="number" label={'Reviewed amount: '+l.label} value={input.manualAmounts?.[l.id]??''} onChange={e=>setInput({...input,manualAmounts:{...input.manualAmounts,[l.id]:num(e.target.value)}})}/>)}{rules.lines.filter((l:any)=>l.annualCap!==null).map((l:any)=><TextField key={l.id} type="number" label={'YTD already deducted: '+l.label} value={input.ytd?.[l.id]??''} onChange={e=>setInput({...input,ytd:{...input.ytd,[l.id]:num(e.target.value)}})}/>)}</Stack><FormControlLabel control={<Checkbox checked={!!input.companyRulesConfirmed} onChange={e=>setInput({...input,companyRulesConfirmed:e.target.checked})}/>} label="I independently checked the employee's local payroll treatment, inputs and company rules."/></Box>;}
export default function WorldwidePayrollEditor({rules,setRules,countries,currencies,preview,busy}:{rules:any;setRules:(v:any)=>void;countries:any[];currencies:any[];preview:(input:any)=>void;busy:boolean}){
 const [input,setInput]=useState<any>(null);
 const updateLine=(index:number,field:string,value:any)=>{setRules({...rules,lines:rules.lines.map((l:any,i:number)=>i===index?{...l,[field]:value}:l)});setInput(null);};
 const textField=(key:string,value:any,onChange:(v:any)=>void,numeric=false)=><TextField key={key} fullWidth sx={{my:1}} label={label(key)} value={value??''} type={numeric?'number':key.toLowerCase().includes('effective')||key==='reviewedOn'?'date':'text'} InputLabelProps={{shrink:true}} onChange={e=>{setInput(null);onChange(numeric?num(e.target.value):e.target.value);}}/>;
 return <Box><Alert severity="warning">Worldwide company-configured mode. No statutory rates are prefilled. A local payroll reviewer must validate your rules and each calculation. Use manual amounts for tax systems these formulas cannot represent. Country selection is not a claim of verified coverage.</Alert>
 <TextField fullWidth select label="Country or territory" value={rules.country} sx={{my:2}} onChange={e=>setRules({...rules,country:e.target.value})}>{countries.map(c=><MenuItem key={c.code} value={c.code}>{c.name} ({c.code})</MenuItem>)}</TextField>
 {textField('subdivision',rules.subdivision,v=>setRules({...rules,subdivision:v}))}<Typography variant="caption">Enter the state/province or “National” after checking local requirements.</Typography>
 <TextField fullWidth select label="Payroll currency" value={rules.currency} sx={{my:2}} onChange={e=>setRules({...rules,currency:e.target.value})}>{currencies.map(c=><MenuItem key={c.code} value={c.code}>{c.code} — {c.decimals} decimal places</MenuItem>)}</TextField>
 {['effectiveFrom','effectiveTo'].map(k=>textField(k,rules[k],v=>setRules({...rules,[k]:v})))}
 <Typography variant="h6">Company policy</Typography>{Object.keys(rules.policy).map(k=>textField(k,rules.policy[k],v=>setRules({...rules,policy:{...rules.policy,[k]:v}}),true))}<Typography>Rates are decimals: 0.04 = 4%. Vacation is an accrual preview only. Overtime classification is not recomputed.</Typography>
 <Typography variant="h6" sx={{mt:3}}>Deductions and employer costs</Typography><Typography>Each line calculates independently from gross or supplied taxable pay. Annualized formulas multiply the basis by pay periods, apply the formula, then divide by pay periods. Exemption is in the selected period; credit is per payment. Caps use the employer-supplied YTD contribution total. Manual amounts are final amounts without automatic adjustments.</Typography>
 {rules.lines.map((l:any,index:number)=><Box key={index} sx={{my:2,p:2,border:1,borderColor:'divider',borderRadius:2}}>{textField('id',l.id,v=>updateLine(index,'id',v))}{textField('label',l.label,v=>updateLine(index,'label',v))}
 {Object.entries({category:['tax','employee_contribution','other_deduction','employer_contribution'],method:['manual','fixed','percentage','progressive'],basis:['gross','taxable'],period:['pay_period','annualized']}).map(([k,options])=><TextField key={k} fullWidth select sx={{my:1}} label={label(k)} value={l[k]} onChange={e=>{if(k==='method'&&e.target.value==='manual'){setRules({...rules,lines:rules.lines.map((x:any,i:number)=>i===index?{...x,method:'manual',annualCap:null,credit:0,exemption:0}:x)});setInput(null);}else updateLine(index,k,e.target.value);}}>{options.map(o=><MenuItem key={o} value={o}>{label(o.replace(/_/g,' '))}</MenuItem>)}</TextField>)}
 {l.method!=='manual'&&<>{l.method==='fixed'&&textField('amount',l.amount,v=>updateLine(index,'amount',v),true)}{l.method==='percentage'&&textField('rate',l.rate,v=>updateLine(index,'rate',v),true)}{['exemption','credit'].map(k=>textField(k,l[k],v=>updateLine(index,k,v),true))}<TextField fullWidth sx={{my:1}} label="Annual contribution cap (blank = no cap)" type="number" value={l.annualCap??''} onChange={e=>updateLine(index,'annualCap',e.target.value===''?null:Number(e.target.value))}/></>}
 {l.method==='progressive'&&<><Typography>Marginal brackets — each rate applies only to the slice above its threshold.</Typography>{l.brackets.map((br:any,j:number)=><Stack key={j} direction="row" spacing={1}>{['above','rate'].map(k=>textField(k,br[k],v=>updateLine(index,'brackets',l.brackets.map((x:any,n:number)=>n===j?{...x,[k]:v}:x)),true))}<Button disabled={j===0} onClick={()=>updateLine(index,'brackets',l.brackets.filter((_:any,n:number)=>n!==j))}>Remove</Button></Stack>)}<Button onClick={()=>updateLine(index,'brackets',[...l.brackets,{above:Number(l.brackets.at(-1).above)+10000,rate:0}])}>Add bracket</Button></>}
 <Button color="error" disabled={rules.lines.length===1} onClick={()=>{setRules({...rules,lines:rules.lines.filter((_:any,i:number)=>i!==index)});setInput(null);}}>Remove line</Button></Box>)}
 <Button onClick={()=>{setRules({...rules,lines:[...rules.lines,{id:'line_'+Date.now(),label:'New deduction',category:'other_deduction',method:'manual',basis:'gross',period:'pay_period',amount:0,rate:0,exemption:0,credit:0,annualCap:null,brackets:[{above:0,rate:0}]}]});setInput(null);}}>Add deduction or employer contribution</Button>
 <Typography variant="h6" sx={{mt:3}}>Local rules review</Typography>{['reviewer','reference','reviewedOn'].map(k=>textField(k,rules.review[k],v=>setRules({...rules,review:{...rules.review,[k]:v}})))}<FormControlLabel control={<Checkbox checked={rules.review.confirmed} onChange={e=>setRules({...rules,review:{...rules.review,confirmed:e.target.checked}})}/>} label="The named reviewer checked the complete rule set for this jurisdiction and period. This is company attestation, not app certification."/>
 <Button sx={{display:'block',my:2}} onClick={()=>setInput(worldwideInput(rules))}>Prepare a preview</Button>{input&&<><WorldwideInputs rules={rules} input={input} setInput={setInput}/><Button disabled={busy||!input.companyRulesConfirmed} onClick={()=>preview(input)}>Calculate preview</Button></>}
 </Box>;
}
