export type UnitFamily='length'|'area'|'volume'|'weight'|'temperature';
export const units:Record<UnitFamily,Record<string,number>>={
 length:{mm:.001,cm:.01,m:1,in:.0254,ft:.3048,yd:.9144,km:1000,mi:1609.344},
 area:{'mm²':1e-6,'cm²':1e-4,'m²':1,'in²':.00064516,'ft²':.09290304,'yd²':.83612736,acre:4046.8564224,ha:10000},
 volume:{ml:1e-6,L:.001,'m³':1,'in³':.000016387064,'ft³':.028316846592,'yd³':.764554857984,'US gal':.003785411784},
 weight:{g:.001,kg:1,lb:.45359237,ton:907.18474,'metric ton':1000},temperature:{C:1,F:1,K:1}
};
export function parseMeasure(input:string):number{
 const s=input.trim().toLowerCase().replace(/[′’]/g,"'").replace(/[″”]/g,'"'); if(!s)throw Error('Enter a measurement');
 const ft=s.match(/^(-?\d+(?:\.\d+)?)\s*(?:ft|')\s*(?:(\d+(?:\.\d+)?)\s*)?(?:(\d+)\s*\/\s*(\d+))?\s*(?:in|")?$/);
 if(ft){const sign=Number(ft[1])<0?-1:1;return Number(ft[1])*.3048+sign*((Number(ft[2]||0)+(ft[3]?Number(ft[3])/Number(ft[4]):0))*.0254);}
 const mixed=s.match(/^(-?\d+)?\s*(?:(\d+)\s*\/\s*(\d+))?\s*(mm|cm|m|in|ft|yd|km|mi)?$/);
 if(!mixed)throw Error('Use 12.5, 3 1/2, or 5\' 7 1/4"'); const whole=Number(mixed[1]||0),frac=mixed[2]?Number(mixed[2])/Number(mixed[3]):0;
 if(mixed[3]&&Number(mixed[3])===0)throw Error('Fraction denominator cannot be zero'); const value=whole<0?whole-frac:whole+frac;
 return value*(units.length[mixed[4]||'ft']);
}
export function convert(value:number,family:UnitFamily,from:string,to:string){
 if(family==='temperature'){const c=from==='C'?value:from==='F'?(value-32)*5/9:value-273.15;return to==='C'?c:to==='F'?c*9/5+32:c+273.15;}
 return value*units[family][from]/units[family][to];
}
export function fraction(value:number,precision=16){const sign=value<0?'-':'';const a=Math.abs(value),whole=Math.floor(a),num=Math.round((a-whole)*precision);if(!num)return `${sign}${whole}`;const gcd=(x:number,y:number):number=>y?gcd(y,x%y):x,g=gcd(num,precision);return `${sign}${whole?whole+' ':''}${num/g}/${precision/g}`;}
export function formatFeet(meters:number,precision=16){const inches=meters/.0254,feet=Math.floor(Math.abs(inches)/12),rem=Math.abs(inches)-feet*12;return `${meters<0?'-':''}${feet}' ${fraction(rem,precision)}"`;}
export type CalcField={key:string;label:string;unit?:string;default?:number};
export type Calculator={id:string;name:string;category:string;description:string;fields:CalcField[];solve:(v:Record<string,number>)=>Record<string,string>};
const n=(v:Record<string,number>,k:string)=>Number(v[k]||0),f=(x:number,d=2)=>Number.isFinite(x)?x.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
export const calculators:Calculator[]=[
 {id:'concrete',name:'Concrete quantity',category:'Construction',description:'Slabs, footings and pads with waste.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'depth',label:'Depth',unit:'in'},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>{const yd=n(v,'length')*n(v,'width')*(n(v,'depth')/12)/27*(1+n(v,'waste')/100);return {'Cubic yards':f(yd,3),'80 lb bags':f(Math.ceil(yd*45),0),'Cubic metres':f(yd*.764554858,3)}}},
 {id:'asphalt',name:'Asphalt tonnage',category:'Construction',description:'Estimate paving material by density.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'depth',label:'Depth',unit:'in'},{key:'density',label:'Density',unit:'lb/ft³',default:145}],solve:v=>({'US tons':f(n(v,'length')*n(v,'width')*n(v,'depth')/12*n(v,'density')/2000,2)})},
 {id:'spacing',name:'Equal spacing',category:'Carpentry',description:'Centers and gaps for balusters, studs or panels.',fields:[{key:'span',label:'Clear span',unit:'in'},{key:'item',label:'Item width',unit:'in'},{key:'count',label:'Item count'}],solve:v=>{const c=Math.max(1,Math.floor(n(v,'count'))),gap=(n(v,'span')-c*n(v,'item'))/(c+1);return {'Equal gap':`${f(gap,3)} in`,'On-center':`${f(gap+n(v,'item'),3)} in`,'Fits':gap>=0?'Yes':'No'}}},
 {id:'square',name:'Check square',category:'Carpentry',description:'Diagonal and 3-4-5 verification.',fields:[{key:'a',label:'Side A',unit:'ft'},{key:'b',label:'Side B',unit:'ft'}],solve:v=>({'Required diagonal':`${f(Math.hypot(n(v,'a'),n(v,'b')),3)} ft`})},
 {id:'stairs',name:'Stair layout',category:'Carpentry',description:'Risers, rise and approximate run.',fields:[{key:'rise',label:'Total rise',unit:'in'},{key:'target',label:'Target riser',unit:'in',default:7.5},{key:'tread',label:'Tread depth',unit:'in',default:10}],solve:v=>{const risers=Math.max(1,Math.ceil(n(v,'rise')/n(v,'target')));return {Risers:f(risers,0),'Actual riser':`${f(n(v,'rise')/risers,3)} in`,Treads:f(Math.max(0,risers-1),0),'Total run':`${f(Math.max(0,risers-1)*n(v,'tread'),2)} in`}}},
 {id:'roof',name:'Roof & slope',category:'Construction',description:'Pitch, rafter and roof area.',fields:[{key:'run',label:'Horizontal run',unit:'ft'},{key:'rise',label:'Rise',unit:'ft'},{key:'length',label:'Building length',unit:'ft'}],solve:v=>{const r=n(v,'run'),rise=n(v,'rise'),raf=Math.hypot(r,rise);return {'Pitch':`${f(rise/r*12,2)} : 12`,'Angle':`${f(Math.atan2(rise,r)*180/Math.PI,2)}°`,'Rafter':`${f(raf,2)} ft`,'Two-slope area':`${f(2*raf*n(v,'length'),1)} ft²`}}},
 {id:'board',name:'Board feet',category:'Carpentry',description:'Lumber volume and cost.',fields:[{key:'thickness',label:'Thickness',unit:'in'},{key:'width',label:'Width',unit:'in'},{key:'length',label:'Length',unit:'ft'},{key:'qty',label:'Quantity',default:1},{key:'cost',label:'Cost / board ft'}],solve:v=>{const bf=n(v,'thickness')*n(v,'width')*n(v,'length')/12*n(v,'qty');return {'Board feet':f(bf,2),'Material cost':`$${f(bf*n(v,'cost'),2)}`}}},
 {id:'circle',name:'Circle & arc',category:'Measure',description:'Area, circumference and arc length.',fields:[{key:'diameter',label:'Diameter'},{key:'angle',label:'Arc angle',unit:'°',default:360}],solve:v=>{const d=n(v,'diameter');return {Area:f(Math.PI*d*d/4,4),Circumference:f(Math.PI*d,4),'Arc length':f(Math.PI*d*n(v,'angle')/360,4)}}},
 {id:'paint',name:'Paint & coverings',category:'Finishing',description:'Wall area, coats and material.',fields:[{key:'perimeter',label:'Room perimeter',unit:'ft'},{key:'height',label:'Wall height',unit:'ft'},{key:'openings',label:'Doors/windows',unit:'ft²'},{key:'coats',label:'Coats',default:2},{key:'coverage',label:'Coverage',unit:'ft²/gal',default:350}],solve:v=>{const area=Math.max(0,n(v,'perimeter')*n(v,'height')-n(v,'openings'));return {'Net area':`${f(area,1)} ft²`,'Gallons':f(Math.ceil(area*n(v,'coats')/n(v,'coverage')),0)}}},
 {id:'ohm',name:"Ohm's law & power",category:'Electrical',description:'Solve voltage, current, resistance and power.',fields:[{key:'voltage',label:'Voltage',unit:'V'},{key:'current',label:'Current',unit:'A'}],solve:v=>({'Resistance':`${f(n(v,'voltage')/n(v,'current'),3)} Ω`,'Power':`${f(n(v,'voltage')*n(v,'current'),2)} W`})},
 {id:'pipe',name:'Pipe volume & flow',category:'Plumbing',description:'Internal volume and fill time.',fields:[{key:'diameter',label:'Inside diameter',unit:'in'},{key:'length',label:'Length',unit:'ft'},{key:'flow',label:'Flow',unit:'US gal/min'}],solve:v=>{const gal=Math.PI*(n(v,'diameter')/2)**2*n(v,'length')*12/231;return {'Volume':`${f(gal,2)} US gal`,'Fill time':`${f(gal/n(v,'flow'),2)} min`}}},
 {id:'landscape',name:'Soil, mulch & gravel',category:'Landscaping',description:'Area material with waste.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'depth',label:'Depth',unit:'in'},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>({'Cubic yards':f(n(v,'length')*n(v,'width')*n(v,'depth')/12/27*(1+n(v,'waste')/100),2)})},
 {id:'dilution',name:'Chemical dilution',category:'Facilities',description:'Safe ratio-based mix quantity.',fields:[{key:'total',label:'Finished volume',unit:'L'},{key:'ratio',label:'Water parts',default:10}],solve:v=>({'Concentrate':`${f(n(v,'total')/(n(v,'ratio')+1),3)} L`,'Water':`${f(n(v,'total')*n(v,'ratio')/(n(v,'ratio')+1),3)} L`})},
 {id:'fuel',name:'Mileage & fuel',category:'Logistics',description:'Trip fuel, efficiency and cost.',fields:[{key:'distance',label:'Distance',unit:'km'},{key:'efficiency',label:'Consumption',unit:'L/100km'},{key:'price',label:'Fuel price',unit:'$/L'}],solve:v=>{const l=n(v,'distance')*n(v,'efficiency')/100;return {Fuel:`${f(l,2)} L`,Cost:`$${f(l*n(v,'price'),2)}`}}}
 ,{id:'slab',name:'Concrete slab',category:'Concrete',description:'Slab volume, waste, bags, truckloads and material cost.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'thickness',label:'Thickness',unit:'in'},{key:'waste',label:'Waste',unit:'%',default:10},{key:'truck',label:'Truck capacity',unit:'yd³',default:10},{key:'cost',label:'Cost',unit:'$/yd³'}],solve:v=>{const area=n(v,'length')*n(v,'width'),yd=area*n(v,'thickness')/12/27*(1+n(v,'waste')/100);return {'Slab area':`${f(area,2)} ft²`,'Concrete':`${f(yd,3)} yd³`,'Cubic metres':`${f(yd*.764554858,3)} m³`,'80 lb bags':f(Math.ceil(yd*45),0),'Truckloads':f(Math.ceil(yd/Math.max(n(v,'truck'),.001)),0),'Material cost':`$${f(yd*n(v,'cost'),2)}`}}}
 ,{id:'slope',name:'Slope & grade',category:'Sitework',description:'Rise/run grade, angle, ratio, pitch and slope length.',fields:[{key:'rise',label:'Rise',unit:'ft'},{key:'run',label:'Horizontal run',unit:'ft'}],solve:v=>{const rise=n(v,'rise'),run=n(v,'run'),length=Math.hypot(rise,run),ratio=rise===0?0:run/Math.abs(rise);return {'Grade':run>0?`${f(rise/run*100,3)}%`:'—','Angle':run>0?`${f(Math.atan2(rise,run)*180/Math.PI,3)}°`:'—','Ratio':rise!==0?`1 : ${f(ratio,3)}`:'Level','Pitch':run>0?`${f(rise/run*12,3)} : 12`:'—','Slope length':`${f(length,3)} ft`}}}
 ,{id:'footing',name:'Continuous footing',category:'Concrete',description:'Concrete for strip footings with waste.',fields:[{key:'length',label:'Total length',unit:'ft'},{key:'width',label:'Width',unit:'in'},{key:'depth',label:'Depth',unit:'in'},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>{const yd=n(v,'length')*n(v,'width')/12*n(v,'depth')/12/27*(1+n(v,'waste')/100);return {'Concrete':`${f(yd,3)} yd³`,'Cubic metres':`${f(yd*.764554858,3)} m³`,'80 lb bags':f(Math.ceil(yd*45),0)}}}
 ,{id:'pier',name:'Concrete pier & column',category:'Concrete',description:'Round pier or column volume.',fields:[{key:'diameter',label:'Diameter',unit:'in'},{key:'depth',label:'Depth/height',unit:'ft'},{key:'count',label:'Quantity',default:1},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>{const yd=Math.PI*(n(v,'diameter')/24)**2*n(v,'depth')*Math.max(0,n(v,'count'))/27*(1+n(v,'waste')/100);return {'Concrete':`${f(yd,3)} yd³`,'Cubic metres':`${f(yd*.764554858,3)} m³`,'80 lb bags':f(Math.ceil(yd*45),0)}}}
 ,{id:'rebar',name:'Rebar grid',category:'Concrete',description:'Two-way reinforcement count, length and approximate weight.',fields:[{key:'length',label:'Slab length',unit:'ft'},{key:'width',label:'Slab width',unit:'ft'},{key:'spacing',label:'Spacing',unit:'in',default:12},{key:'lap',label:'Lap/waste',unit:'%',default:10},{key:'weight',label:'Bar weight',unit:'lb/ft',default:.668}],solve:v=>{const s=Math.max(n(v,'spacing')/12,.001),barsL=Math.ceil(n(v,'width')/s)+1,barsW=Math.ceil(n(v,'length')/s)+1,total=(barsL*n(v,'length')+barsW*n(v,'width'))*(1+n(v,'lap')/100);return {'Lengthwise bars':f(barsL,0),'Crosswise bars':f(barsW,0),'Total rebar':`${f(total,1)} ft`,'Approx. weight':`${f(total*n(v,'weight'),1)} lb`}}}
 ,{id:'masonry',name:'Block, brick & mortar',category:'Masonry',description:'Wall units with openings and waste.',fields:[{key:'length',label:'Wall length',unit:'ft'},{key:'height',label:'Wall height',unit:'ft'},{key:'openings',label:'Openings',unit:'ft²'},{key:'unitArea',label:'Unit face area',unit:'in²',default:128},{key:'waste',label:'Waste',unit:'%',default:7}],solve:v=>{const area=Math.max(0,n(v,'length')*n(v,'height')-n(v,'openings')),count=Math.ceil(area*144/Math.max(n(v,'unitArea'),.001)*(1+n(v,'waste')/100));return {'Net wall area':`${f(area,2)} ft²`,'Units required':f(count,0),'Mortar allowance':`${f(count*.025,2)} ft³`}}}
 ,{id:'excavation',name:'Excavation & backfill',category:'Sitework',description:'Bank volume, swell and remaining backfill.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'depth',label:'Depth',unit:'ft'},{key:'swell',label:'Swell',unit:'%',default:20},{key:'structure',label:'Structure displacement',unit:'yd³'}],solve:v=>{const bank=n(v,'length')*n(v,'width')*n(v,'depth')/27,loose=bank*(1+n(v,'swell')/100);return {'Bank volume':`${f(bank,2)} yd³`,'Loose volume':`${f(loose,2)} yd³`,'Backfill':`${f(Math.max(0,bank-n(v,'structure')),2)} yd³`}}}
 ,{id:'trench',name:'Trench volume',category:'Sitework',description:'Excavation, bedding and spoil volume.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'in'},{key:'depth',label:'Depth',unit:'in'},{key:'bedding',label:'Bedding depth',unit:'in',default:6}],solve:v=>{const yd=n(v,'length')*n(v,'width')/12*n(v,'depth')/12/27,bed=n(v,'length')*n(v,'width')/12*n(v,'bedding')/12/27;return {'Excavation':`${f(yd,3)} yd³`,'Bedding':`${f(bed,3)} yd³`,'Spoil':`${f(Math.max(0,yd-bed),3)} yd³`}}}
 ,{id:'drywall',name:'Drywall materials',category:'Finishing',description:'Sheets, screws and compound allowance.',fields:[{key:'area',label:'Surface area',unit:'ft²'},{key:'sheetArea',label:'Sheet area',unit:'ft²',default:32},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>{const adjusted=n(v,'area')*(1+n(v,'waste')/100),sheets=Math.ceil(adjusted/Math.max(n(v,'sheetArea'),.001));return {'Adjusted area':`${f(adjusted,1)} ft²`,'Sheets':f(sheets,0),'Screws':f(Math.ceil(sheets*32),0),'Compound':`${f(Math.ceil(sheets/10),0)} × 4.5 gal pails`}}}
 ,{id:'tile',name:'Tile & flooring',category:'Finishing',description:'Floor coverage, waste, cartons and cost.',fields:[{key:'length',label:'Length',unit:'ft'},{key:'width',label:'Width',unit:'ft'},{key:'waste',label:'Waste',unit:'%',default:10},{key:'carton',label:'Coverage/carton',unit:'ft²',default:20},{key:'cost',label:'Cost',unit:'$/ft²'}],solve:v=>{const area=n(v,'length')*n(v,'width'),buy=area*(1+n(v,'waste')/100);return {'Room area':`${f(area,2)} ft²`,'Purchase area':`${f(buy,2)} ft²`,'Cartons':f(Math.ceil(buy/Math.max(n(v,'carton'),.001)),0),'Material cost':`$${f(buy*n(v,'cost'),2)}`}}}
 ,{id:'roofing',name:'Roofing materials',category:'Roofing',description:'Roof squares, bundles and underlayment.',fields:[{key:'length',label:'Plan length',unit:'ft'},{key:'width',label:'Plan width',unit:'ft'},{key:'pitch',label:'Pitch rise',unit:'in/12',default:6},{key:'waste',label:'Waste',unit:'%',default:12}],solve:v=>{const factor=Math.sqrt(1+(n(v,'pitch')/12)**2),area=n(v,'length')*n(v,'width')*factor*(1+n(v,'waste')/100),sq=area/100;return {'Roof area':`${f(area,1)} ft²`,'Squares':f(sq,2),'Bundles':f(Math.ceil(sq*3),0),'Underlayment rolls':f(Math.ceil(area/400),0)}}}
 ,{id:'deck',name:'Deck boards & joists',category:'Carpentry',description:'Decking rows, linear feet and joist count.',fields:[{key:'length',label:'Deck length',unit:'ft'},{key:'width',label:'Deck width',unit:'ft'},{key:'board',label:'Board face',unit:'in',default:5.5},{key:'gap',label:'Board gap',unit:'in',default:.25},{key:'joist',label:'Joist spacing',unit:'in',default:16},{key:'waste',label:'Waste',unit:'%',default:10}],solve:v=>{const rows=Math.ceil(n(v,'width')*12/Math.max(n(v,'board')+n(v,'gap'),.001)),linear=rows*n(v,'length')*(1+n(v,'waste')/100),joists=Math.ceil(n(v,'length')*12/Math.max(n(v,'joist'),.001))+1;return {'Board rows':f(rows,0),'Decking':`${f(linear,1)} linear ft`,'Joists':f(joists,0)}}}
 ,{id:'fence',name:'Fence materials',category:'Carpentry',description:'Posts, sections, rails and pickets.',fields:[{key:'length',label:'Fence length',unit:'ft'},{key:'section',label:'Section length',unit:'ft',default:8},{key:'rails',label:'Rails/section',default:2},{key:'picket',label:'Picket plus gap',unit:'in',default:6}],solve:v=>{const sections=Math.ceil(n(v,'length')/Math.max(n(v,'section'),.001));return {Sections:f(sections,0),Posts:f(sections+1,0),Rails:f(sections*n(v,'rails'),0),Pickets:f(Math.ceil(n(v,'length')*12/Math.max(n(v,'picket'),.001)),0)}}}
 ,{id:'insulation',name:'Insulation',category:'Finishing',description:'Net area, packages and estimated cost.',fields:[{key:'length',label:'Total wall length',unit:'ft'},{key:'height',label:'Wall height',unit:'ft'},{key:'openings',label:'Openings',unit:'ft²'},{key:'coverage',label:'Coverage/package',unit:'ft²',default:40},{key:'waste',label:'Waste',unit:'%',default:10},{key:'cost',label:'Cost/package',unit:'$'}],solve:v=>{const area=Math.max(0,n(v,'length')*n(v,'height')-n(v,'openings'))*(1+n(v,'waste')/100),packs=Math.ceil(area/Math.max(n(v,'coverage'),.001));return {'Purchase area':`${f(area,1)} ft²`,Packages:f(packs,0),'Material cost':`$${f(packs*n(v,'cost'),2)}`}}}
 ,{id:'voltage-drop',name:'Voltage drop',category:'Electrical',description:'Single-phase copper voltage-drop estimate.',fields:[{key:'voltage',label:'System voltage',unit:'V'},{key:'current',label:'Current',unit:'A'},{key:'length',label:'One-way length',unit:'ft'},{key:'resistance',label:'Conductor resistance',unit:'Ω/1000ft',default:1.588}],solve:v=>{const drop=2*n(v,'length')*n(v,'current')*n(v,'resistance')/1000;return {'Voltage drop':`${f(drop,3)} V`,'Drop percent':n(v,'voltage')>0?`${f(drop/n(v,'voltage')*100,3)}%`:'—','Load voltage':`${f(n(v,'voltage')-drop,3)} V`}}}
 ,{id:'hvac-airflow',name:'HVAC airflow',category:'HVAC',description:'Room air changes and approximate airflow.',fields:[{key:'length',label:'Room length',unit:'ft'},{key:'width',label:'Room width',unit:'ft'},{key:'height',label:'Room height',unit:'ft'},{key:'ach',label:'Air changes/hour',default:6}],solve:v=>{const volume=n(v,'length')*n(v,'width')*n(v,'height');return {'Room volume':`${f(volume,1)} ft³`,'Required airflow':`${f(volume*n(v,'ach')/60,1)} CFM`}}}
 ,{id:'equipment-cost',name:'Equipment operating cost',category:'Logistics',description:'Fuel, labour, rental and total job cost.',fields:[{key:'hours',label:'Operating hours',unit:'h'},{key:'fuel',label:'Fuel use',unit:'L/h'},{key:'fuelPrice',label:'Fuel price',unit:'$/L'},{key:'rental',label:'Rental',unit:'$/h'},{key:'labour',label:'Labour',unit:'$/h'}],solve:v=>{const fuel=n(v,'hours')*n(v,'fuel')*n(v,'fuelPrice'),rental=n(v,'hours')*n(v,'rental'),labour=n(v,'hours')*n(v,'labour');return {'Fuel cost':`$${f(fuel,2)}`,'Rental cost':`$${f(rental,2)}`,'Labour cost':`$${f(labour,2)}`,'Total cost':`$${f(fuel+rental+labour,2)}`}}}
];
